### ISSUE TITLE
Make `tmpfs` runner configuration accessible

### ISSUE THREAD

**Issue by fpalluel** [npalm/terraform-aws-gitlab-runner#104]
Hello,

First, thank you for this module, it makes setting up a CI infrastructure a breeze ;-)

We are currently facing performances issues during docker push/pull operations due to IOPS limitations on EBS storage (see [AWS documentation](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html))
We successfully tried to mount `/var/lib/docker` to `tmpfs`, using the [runner's tmpfs configurations](https://docs.gitlab.com/runner/executors/docker.html#mounting-a-directory-in-ram).

Those configurations cannot be customized in the module so the suggestion is, for instance, to add `runners_services_tmpfs` and `runners_tmpfs` variables. What would you think ?

**Comment by npalm** [comment]
Thank you for adding this suggestion. Good idea! Would you like to create PR?

**Comment by fpalluel** [comment]
Hello,
Ok, I'll create the PR ;-)

**Comment by npalm** [comment]
I would say `runners_tmpfs` variable

**Comment by roock** [comment]
@fpalluel did you already start working with the PR? I need this feature too now, so if you didn't start yet, I'm goging to start soon

**Comment by npalm** [comment]
@roock feel free to propose a PR

**Comment by fpalluel** [comment]
Hello, sorry for the late reply.
Right now i have hardcoded the tmpfs conf like that : 
```
[runners.docker.tmpfs]
  "/var/lib/docker" = "rw,noexec"
[runners.docker.services_tmpfs]
  "/var/lib/docker" = "rw,noexec"
```

To make them configurable, do we want to pass a single map for both `tmpfs` and `services_tmpfs`. Such as: 
```
runners_tmpfs = {
  "/var/lib/docker" = "rw,noexec"
  "/var/cache/" = " "rw,noexec"
}
```

Or do we make them configurable independently ?

**Comment by npalm** [comment]
@fpalluel @roock just wondering is one of you still looking to this issue?

**Comment by roock** [comment]
@npalm  and @fpalluel  I've created a PR for Terraform 0.11 (still need to upgrade our systems  to 0.12)

**Comment by npalm** [comment]
Feature is now merged to terraform011 branch, thanks to @roock I will port the change to terraform 0.12 as well.
