### ISSUE TITLE
Runner tags namespaced with ":" are split wrong in userdata.

### ISSUE THREAD

**Issue by tony-harverson-moonpig** [npalm/terraform-aws-gitlab-runner#111]
If runner tags are passed in using the "tags" variable, and those runner tags contain ":" (which we're using for namespacing tags), the string passed into the gitlab runner's user_data is incorrect, splitting the name of the key into two (or more) strings.

https://github.com/Moonpig/terraform-aws-gitlab-runner/commit/f97efebb6ca3c9ad83d78d563aefeeb7fdd414dd is an alternative (tf 12 only) strategy to processing the keys, which treats those keys correctly. 

If you're okay with that implementation, I can add an example to runner-default(?) and PR this change.

**Comment by npalm** [comment]
@tony-harverson-moonpig thanks for creating the issue, will check in the next days

**Comment by npalm** [comment]
Looks good, please feel free to create a PR, terraform 0.12 is now the default. (branche develop)
