### ISSUE TITLE
Add SSM session manager support

### ISSUE THREAD

**Issue by int128** [npalm/terraform-aws-gitlab-runner#121]
It would be nice if this module supports [AWS Systems Manager Session Manager](https://docs.aws.amazon.com/systems-manager/latest/userguide/session-manager.html). We can access runners in a private subnet by the session manager instead of a bastion and SSH.

We need the following extra work:

- Add an input parameter like `enable_gitlab_runner_ssm_access` (boolean).
- Add [the session manager permissions](https://docs.aws.amazon.com/systems-manager/latest/userguide/getting-started-add-permissions-to-existing-profile.html) to the instance role of runners.
- Do not create a ssh key pair resource if `ssh_public_key = ""` and `ssh_key_pair = ""`.

**Comment by npalm** [comment]
@int128 would you like to propose a PR?

**Comment by npalm** [comment]
Just dit a quick check, got it working manual. Need to attached the policy:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ssmmessages:CreateControlChannel",
                "ssmmessages:CreateDataChannel",
                "ssmmessages:OpenControlChannel",
                "ssmmessages:OpenDataChannel"
            ],
            "Resource": "*"
        }
    ]
}
```

and `arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore`

**Comment by npalm** [comment]
The instance role is currently an output of the module, so adding the required permissions is already possible. But I still like to proposal to add this as an extra feature.

**Comment by npalm** [comment]
@int128 do you have time to have a look of the change in branch #127

**Comment by int128** [comment]
@npalm Awesome! Looks good to me. Thank you for your great work!
