### ISSUE TITLE
Do Not chmod local keys when they are stipulated (Windows Compat)

### ISSUE THREAD

**Issue by DarwinJS** [npalm/terraform-aws-gitlab-runner#126]
I'm running this on Windows.  Since the template tries to chmod keys that it generates, I overrode with a key I already had.  However, it still tries to chmod.

On an apply of the runner-default example, this seemed to be the only blocker for Windows execution.

Some Possible Fix Implementations:
1. Make permissions commands natively compatible with Windows.
2. Assume that permissions on stipulated (non-generated) keys are correct and do not run permissions commands on them - let it fall through to ssh error or maybe warn that permissions were not verified.  

I'm not sure it is a good idea to change permissions on existing keys in any case?

Windows 10, PowerShell 7.0.0-preview.3, Terraform 12.7

**Comment by npalm** [comment]
@DarwinJS thanks for reporting the issue. I do not use windows so was not aware this limitation. I agree it could be debated to generate the keys and / or change permissions. The intend of the samples is to get started. I guess the generated keys are not working on windows at all? Guess you need to convert them for putty or so.

Could you please check if you replace the `null_resouce` with the one below could solve your issue?

```

resource "null_resource" "file_permission" {
  depends_on = [local_file.private_ssh_key]

  provisioner "local-exec" {
    command = format("chmod 600 %s", var.private_ssh_key_filename)
    interpreter = ["/bin/bash", "-c"]
  }
}
```

**Comment by DarwinJS** [comment]
@npalm - Windows Services for Linux is not preinstalled on Windows.

I commented out the section that does the chmod and allowed it to use the generated keys and it does not generate an error.  Though I have not tried to SSH the instance.

I also found that on teardown it tries to run a bash script

![image](https://user-images.githubusercontent.com/11597190/64215882-8bebc480-ce84-11e9-86cb-7401b8af7845.png)

**Comment by DarwinJS** [comment]
Ok when Windows Services for Linux (WSL) is installed, the following additional line works (They are untested since I had WSL installed):

`interpreter = ["bash", "-c"]`

However, the file permissions are not altered (or at least they are not set correctly).  FYI - I do the Windows chocolatey package for the MIcrosoft port of OpenSSH portable.

I put together command line instructions for installing ubuntu WSL on windows:

````
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux
Invoke-WebRequest -Uri https://aka.ms/wsl-ubuntu-1604 -OutFile Ubuntu.appx -UseBasicParsing
Add-AppxPackage .\Ubuntu.appx
bash #first time setup
bash -c "sudo apt update && sudo apt --assume-yes install jq awscli"
bash -c "aws configure" #make it match native windows creds
````
After correcting the EOL character in "../../ci/bin/cancel-spot-instances.sh runners-default" is was able to run.
If you create a .gitattributes with the following it might fix the EOL character issue automatically:
`.sh      text eol=lf`

cancel-spot-instances.sh did get this error:
![image](https://user-images.githubusercontent.com/11597190/64219893-5c918380-ce95-11e9-9c82-8cb78d091b89.png)
