### ISSUE TITLE
Explain how to update the GitLab Runner in the README

### ISSUE THREAD

**Issue by lsorber** [npalm/terraform-aws-gitlab-runner#136]
Hi, thanks for this nice Terraform module!

Could you add a section to the README that explains what the best way to update the GitLab Runner is (assuming the user has previously set up a GitLab Runner with this module)?

**Comment by npalm** [comment]
Thanks, good catch. Would you like to make a proposal via a PR?

**Comment by lsorber** [comment]
Sure, except I'm not sure what the process is. Here's my guess: changing the `gitlab_runner_version` variable and then running `terraform apply` might do the trick.

**Comment by npalm** [comment]
We do not use a very smooth process yet. We currently
- bump the version
- apply the change
- disable the runner (pause) in gitlab
- terminate the runner instance, which will trigger the creation of a new agent (via the as group)
- enable the the runner in gitlab

**Comment by lsorber** [comment]
OK, thanks, I'll try that once there's a new version with significant improvements. If it works, I'll probably contribute a small PR with the necessary steps in detail.

**Comment by roock** [comment]
> We do not use a very smooth process yet. We currently
> 
>     * bump the version
> 
>     * apply the change
> 
>     * disable the runner (pause) in gitlab
> 
>     * terminate the runner instance, which will trigger the creation of a new agent (via the as group)
> 
>     * enable the the runner in gitlab


Maybe it is easier to just stop the gitlab runner by ssh `sudo gitlab-runner stop`. It will stop accepting new jobs and wait for all jobs to finish.
Also you should consider terminating all the docker-machine instances. Next week I might work on an ansible script to do all that.

**Comment by npalm** [comment]
Runner will update now by replacing the auto scaling group, so I will close the issue
