### ISSUE TITLE
Docker-machine Cert Generation Issue

### ISSUE THREAD

**Issue by roock** [npalm/terraform-aws-gitlab-runner#143]
The docker-machine cert generation has issues if multiple machines are spin up at the same time.  This was (partly) fixed in #83  but I think the given work around does not fully solve the issue. For me the certificates are generated in /.docker/machine instead of /root/.docker/machine. This has been discussed e.g. in https://github.com/docker/machine/issues/3845#issuecomment-280389178 

I propose to explicitly set USER and HOME before creating the dummy machine. I would also suggest to remove the dummy machine again as it is not needed after creation of the certificates.

**Comment by npalm** [comment]
Port fix for terraform 0.12, still need to check
