### ISSUE TITLE
Pass IAM policies ARNs as a list to an input variable

### ISSUE THREAD

**Issue by bsuv** [npalm/terraform-aws-gitlab-runner#155]
It would be much more convenient if one could reuse existing IAM policies (custom or managed) and just pass a list of ARNs that would be attached to the Runner's roles

**Comment by npalm** [comment]
Good idea, feel free to create a PR

**Comment by kayman-mk** [comment]
Is this under development? I am also interested in this feature but want to avoid coding it twice.

**Comment by npalm** [comment]
@kayman-mk as for I know there is not development on this issue, looking forward to a PR
