### ISSUE TITLE
Runners should remove themselves on instance termination

### ISSUE THREAD

**Issue by pshuman-heb** [npalm/terraform-aws-gitlab-runner#163]
Right now, when a runner instance is terminated, it leaves behind a phantom runner registration in Gitlab that takes a few minutes to go unhealthy, and requires you to go into Gitlab to remove it. It should be easy enough to use the stored access token to fire off a `DELETE` request as [documented in the Gitlab API](https://docs.gitlab.com/ee/api/runners.html#remove-a-runner), and hook that script up to the instance termination alerts/scripts.

There's a number of ways to set up on-terminate scripts in EC2, and I'm not totally familiar with the pros and cons of each of them, but my understanding is that we should be able to just drop a script into `/etc/rc0.d/SCRIPTNAME` and have that fire off a request to remove the runner on system shutdowns? The other way that may be better for use with Spot instances would be a cron script that would check the Termination notices from the instance metadata service and remove when that pops up? That could also help to prevent jobs getting scheduled right before the runner is going to die.

I'll see about making a PR for this - but if anyone has some insight on the proper way to do this, it's perhaps a bit beyond my limited UNIX knowledge to say which way is best.

**Comment by ado120** [comment]
I also agree that when destroying the gitlabrunners via terraform destroy, the runners themselves should be removed from GitLab Runners page

**Comment by pshuman-heb** [comment]
@ado120 I think this will work as a catch-all for both that situation, and for instance termination inside of AWS, either natural reboots, ASG actions, or Spot Instance terminations.
