### ISSUE TITLE
docker runner fail to upload artifacts

### ISSUE THREAD

**Issue by riccardomc** [npalm/terraform-aws-gitlab-runner#169]
Hi, thanks for this module.

I am running into an issue with newly created gitlab runners. I am unable to upload artifacts to gitlab.com and I suspect it is because the url is wrong. The issue is well described here:

https://gitlab.com/gitlab-org/gitlab-runner/issues/4083

**Comment by npalm** [comment]
@riccardomc thanks, released the fix in 4.10.0
