### ISSUE TITLE
Tags for EC2 instances

### ISSUE THREAD

**Issue by Glen-Moonpig** [npalm/terraform-aws-gitlab-runner#175]
We have a requirement to apply certain tags to EC2 instances only. The module currently only has one 'tags' input variable, which applies to all resources.
We are considering adding a new input variable for tags that will be applied to the EC2 instances only (as well as the tags being applied currently).

```
variable "runner_tags" {
  description = "Map of tags that will be added to created EC2 resources."
  type        = map(string)
  default     = {}
}
```

Is this something that you might merge in? Any other suggestions?

**Comment by npalm** [comment]
@Glen-Moonpig yes a PR is welkome! Beware that there are two types of instances. Also you can have a look at the variable `overrides` this variable overwrite defaults for names of the instance
