### ISSUE TITLE
Update to Amazon Linux 2

### ISSUE THREAD

**Issue by roock** [npalm/terraform-aws-gitlab-runner#177]
Quoting https://aws.amazon.com/amazon-linux-ami/faqs/
Amazon Linux Version 1 (2018.03) will be out of support on June 30, 2020. Instead Amazon Linux Version 2 should be used. (there are some hints in the README which say that it's currently not working).

My suggestion would be to also try to support Ubuntu as a secondary installation target. Hopefully I have time in the next weeks to take a look into it.

**Comment by npalm** [comment]
Thanks @chludwig-haufe
