### ISSUE TITLE
Name is not configured even though `runners_name` is set

### ISSUE THREAD

**Issue by lsorber** [npalm/terraform-aws-gitlab-runner#178]
After having just deployed a GitLab Runner with the latest version of this module with `runners_name` set, it seems that GitLab doesn't know the newly created Runner's name:
![image](https://user-images.githubusercontent.com/4543654/73157679-14902900-40e2-11ea-99b5-000ac3bd762f.png)

**Comment by Glen-Moonpig** [comment]
I think this might be a GitLab issue. The name should still be visible on the settings/ci_cd page. I have never figured out how to get a value into that Name field.

**Comment by npalm** [comment]
I have just create a runner based on the default example. The name of the runner shows correctly in gitlab

<img width="482" alt="Screenshot 2020-02-03 at 21 21 00" src="https://user-images.githubusercontent.com/11609620/73687920-477e8200-46cb-11ea-9f18-cfeb92c7056b.png">

**Comment by npalm** [comment]
Closting since it is not a issue at this infrastructure repo for the github runners
