### ISSUE TITLE
Private ECR image in runners

### ISSUE THREAD

**Issue by realsby** [npalm/terraform-aws-gitlab-runner#189]
I shared an example in the comments.

**Comment by realsby** [comment]
I know this issue is not about your plugin. 
But I wish at least you have an example to support private ecr images in runners with docker machine.

**Comment by realsby** [comment]
After I installed amazon-ecr-credential-helper to both instance, it started to work. Here the full sample for the ones who wants to use private ECR image in runner:

```
module "gitlab_runner" {
  source  = "npalm/gitlab-runner/aws"
  version = "4.11.1"

  userdata_pre_install = "sudo yum install amazon-ecr-credential-helper -y"
  userdata_post_install = "echo '#!/bin/bash\nsudo apt-get update\nsudo apt-get install amazon-ecr-credential-helper -y' >> /var/tmp/user_data.sh"
  docker_machine_options = ["amazonec2-userdata=/var/tmp/user_data.sh"]
  runners_environment_vars = ["DOCKER_AUTH_CONFIG={\"credHelpers\":{\"${local.ecr_aws_account_id}.dkr.ecr.${local.region}.amazonaws.com\": \"ecr-login\"}}"]

  ami_filter = {
    name = ["amzn2-ami-hvm-2.*-x86_64-ebs"]
  }
  runner_ami_filter = {
    name = ["ubuntu/images/hvm-ssd/ubuntu-eoan-19.10-amd64-server-*"]
  }

  gitlab_runner_version    = "12.8.0"
  # ........
}

resource "aws_iam_role_policy_attachment" "allow_ecr_full_agent" {
  role       = "${module.gitlab_runner.runner_agent_role_name}"
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
}

resource "aws_iam_role_policy_attachment" "allow_ecr_full" {
  role       = "${module.gitlab_runner.runner_role_name}"
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
}

```

**Comment by DavidGamba** [comment]
@realsby This setup isn't working for me, would you mind verifying this example is still valid?
Thanks!

**Comment by realsby** [comment]
@DavidGamba Yes it is working. This is the recent copy.

```
module "sas_gitlab_default" {
  source  = "npalm/gitlab-runner/aws"
  version = "4.13.0"

  userdata_pre_install     = "sudo yum install amazon-ecr-credential-helper -y"
  userdata_post_install    = "echo '#!/bin/bash\nsudo apt-get update\nsudo apt-get install amazon-ecr-credential-helper -y' > /var/tmp/user_data.sh"
  docker_machine_options   = ["amazonec2-userdata=/var/tmp/user_data.sh"]
  runners_environment_vars = ["DOCKER_AUTH_CONFIG={\"credHelpers\":{\"${local.ecr_aws_account_id}.dkr.ecr.${local.region}.amazonaws.com\": \"ecr-login\"}}"]

  ami_filter = {
    name = ["amzn2-ami-hvm-2.0.20200304.0-x86_64-ebs"]
  }

  runner_ami_filter = {
    name = ["ubuntu/images/hvm-ssd/ubuntu-eoan-19.10-amd64-server-20200325"]
  }

}
```

**Comment by DavidGamba** [comment]
@realsby thanks so much, just for clarity with that I can just call the image directly in my .gitlab-ci.yml file right?

```
job1:
  image: "391495333905.dkr.ecr.us-west-2.amazonaws.com/dgamba-deployments-base:latest"
  ...
```

Or are you doing anything different there?

**Comment by sjoerd-dijkstra** [comment]
Hi guys, we're trying to setup the same thing, not having it all working yet. (see #234 for details). Is above configuration still working @realsby , @DavidGamba ?

Do your runners maybe also report?
> gitlab-runner: Failed to process runner builds error: failed to update executor: no free machines that can process builds

It seems our `runner-agent` is not successfully pushing the user-data to the actual docker machine runners..

Thanks in advance!

**Comment by realsby** [comment]
@sjoerd-dijkstra I recently updated everything, runner version, os ami images, this module version and they all worked fine without any problem with the ecr. 

I am not sure what is the problem that you are facing with, i saw you also give ECR full permission to everything.
The only thing that i realize you define runners_image but when i check my terraform i did not set anything so it is using the default value of the module. Maybe its because of the docker version i don't know.
