### ISSUE TITLE
Where are the machine runner pem keys

### ISSUE THREAD

**Issue by alvarodelvalle** [npalm/terraform-aws-gitlab-runner#196]
Hi, 👋 firstly, awesome product! I am wondering when I can find the pem file so I can connect to machine runners? I am running the project with docker-machine executor with the agent runner configured for SSM. When I connect to the agent runner, I see that there are directories for each machine runner in /root/.docker/. In any given machine directory, there are a few pem files, which I tried using to connect to a machine runner with no success. Which begs to question, where are the machine runner pem keys?

**Comment by npalm** [comment]
Keys for the machines are on the agent instance, should be in a docker or docker machine dir. Just login via SSM to the agent instance and next login dot the machine with `docker-machine ssh <id>`

**Comment by npalm** [comment]
@alvarodelvalle shall we close the issue?
