### ISSUE TITLE
docker+machine TLS config challenges

### ISSUE THREAD

**Issue by alvarodelvalle** [npalm/terraform-aws-gitlab-runner#197]
I spent all day today trying different configurations to utilize TLS on a docker+machine executor configuration. I've read a lot of material in this repo and elsewhere. 
This seems to be the way 'it should' work:
## runners.docker configuration 
``` bash
[runners.docker]
    tls_verify = true
    image = "docker:18.03.1-ce"
    privileged = true
    disable_cache = false
    volumes = ["/cache","/certs/client"]
```  

## .gitlab-ci.yaml
```variables:
  DOCKER_TLS_CERTDIR: "/certs"
...
  before_script:
  - export DOCKER_DRIVER='overlay2'
  - export DOCKER_HOST='tcp://docker:2376/'
```  

## Actual results
```bash
$ export DOCKER_DRIVER='overlay2'
$ export DOCKER_HOST='tcp://0.0.0.0:2376/'
$ docker build --no-cache -t $REPOSITORY_URL .
time="2020-03-13T21:29:43Z" level=error msg="failed to dial gRPC: cannot connect to the Docker daemon. Is 'docker daemon' running on this host?: dial tcp 0.0.0.0:2376: connect: connection refused"
context canceled
ERROR: Job failed: exit code 1
```  
## Other configs I've tried
```bash
[runners.docker]
    tls_verify = false
...
## .gitlab-ci.yaml
  DOCKER_TLS_CERTDIR: "/certs"
$ export DOCKER_HOST='tcp://0.0.0.0:2375/'
```  
This actually complains that the '/certs' directory is invalid

My current config is 

```bash
[runners.docker]
    tls_verify = false
...
## .gitlab-ci.yaml
  DOCKER_TLS_CERTDIR: ""
$ export DOCKER_HOST='tcp://0.0.0.0:2375/'
```  
And this yields a successful docker build but I worry about it not being TLS. Ingress is not exposed to the internet so I am not too worried but I only see this as a temporary workaround

Thank you in advance!

**Comment by npalm** [comment]
Did you have tried a newer docker version?  Some TLS things were changed around version 18.03 if I remember  correctly.

**Comment by npalm** [comment]
@alvarodelvalle Did you had time to check my suggestion, shall we close the issue?

**Comment by alvarodelvalle** [comment]
I've tried different docker versions. I decided to use k8s integration instead.
