### ISSUE TITLE
Bucket lifecycle policy prefix should be configurable

### ISSUE THREAD

**Issue by realsby** [npalm/terraform-aws-gitlab-runner#200]
I found my cache bucket size is over 300 GB! It has files from a few months ago. But I already set the cache_expiration_days to 5.  Then I found it create a lifecycle policy for the objects with prefix : runner/, but all my objects stored in prefix : project/ folder. I don't know why it is working like this. But I wish that you apply the lifecycle rule for the whole bucket, or you can make a variable for the prefix part.

**Comment by npalm** [comment]
@realsby good catch. Feel free to propose a PR. A variable for with a prefix sounds like a easy fix without breaking any backward compatibility.

**Comment by npalm** [comment]
Added to release 4.13.0

**Comment by kayman-mk** [comment]
That's what I have seen too. The prefix in by cache bucket is `project/` too.
