### ISSUE TITLE
Existed Cache bucket usage policy attachment to docker machine is missing

### ISSUE THREAD

**Issue by realsby** [npalm/terraform-aws-gitlab-runner#206]
I am following this sample, 
https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/examples/runner-public/main.tf

when you create cache bucket outside of the module, even if you pass the related policy arn into  cache_bucket variable, it is not attached because create is false..
```
  cache_bucket = {
    create = false
    policy = "${module.cache.policy_arn}"
    bucket = "${module.cache.bucket}"
  }
```
 So you have to attach it, outside of the module. If this is the case you need to update example. If not why we are passing the policy into variable.

**Comment by npalm** [comment]
@realsby good catch, thanks for creating the issue
