### ISSUE TITLE
Leftover instances, buggy startup and other docker-machine issues

### ISSUE THREAD

**Issue by fliphess** [npalm/terraform-aws-gitlab-runner#209]
I'm running into some issues using the docker-machine setup: 

Due to some bugs in the docker-machine setup for AWS, there are many leftover nodes that are not cleaned up after running tasks or nodes that are configured but never used and never removed, bringing up the cost for our runners. 

I've seen many bug reports on gitlab of other docker-machine users running into issues like this (the biggest issue is not being able to set `IdleCount` to 1, so there's always an extra machine available for running tasks, causing extremely long waittimes for jobs to start. 

As docker-machine is in maintenance mode, these issues will not be fixed, but I noticed there is a fork by gitlab itself fixing some of the issues I'm running into. 

Have other users of this module experimented with using the docker-machine fork by gitlab instead of the regular one? I'm curious if people notice improvement and if it's worth a PR to allow using the gitlab fork instead? 

The releases of the gitlab docker-machine fork can be found here: https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/releases

**Comment by npalm** [comment]
@fliphess We do not face this issue, runners are removed without an issue. We had those kind of issues pre docker-machine 0.16. Yes I am aware of the gitlab fork of docker-machine. Did not had the time to integrate and test it yet.

**Comment by fliphess** [comment]
@npalm How many instances are you running in your scaling setup? 

I noticed the `IdleCount` thing I run into (https://gitlab.com/gitlab-org/gitlab-runner/issues/1423) only appears with smaller setups. Do you happen to have worked around this already or is it not an issue for  you?

**Comment by npalm** [comment]
No, we run with 2 agents. One having up to 10 runners and another one up to 5. The config of the first one below

```
  runners_idle_time             = 600
  runners_idle_count            = 2
  runners_off_peak_timezone     = "Europe/Amsterdam"
  runners_off_peak_idle_count   = 0
  runners_off_peak_idle_time    = 300
  runners_concurrent            = 10
  runners_root_size             = 16
  runners_max_builds            = 10
  runners_off_peak_periods      = "[\"* * 0-8,18-23 * * mon-fri *\", \"* * * * * sat,sun *\"]"
  docker_machine_instance_type  = "t3.large"
```
Only issue we have time to time is a full disk. For the rest it all works

**Comment by fliphess** [comment]
Thanks! I'll close this issue as the problem I run into is not in the module but either in my setup or docker-machine which are both out of scope of this issue :) 

Thanks for the information! 👍

**Comment by DavidGamba** [comment]
A way to define the use of the gitlab fork of docker machine would be beneficial.

**Comment by fliphess** [comment]
I'll see if I can create a PR soon :) 👍
