### ISSUE TITLE
enable_forced_updates seems backwards

### ISSUE THREAD

**Issue by martinhanzik** [npalm/terraform-aws-gitlab-runner#213]
I'm not sure if I'm just not understanding this correctly, but the behaviour seems to be inverted. I have 2 runners set up, one with enable_forced_updates set to true, and one with default (false). Both of them have a change in their user_data, so the launch configuration is replaced. The ASG for the runner with enable_forced_updates is just updated to point to the new configuration, while the ASG with enable_forced_updates set to false is recreated.

Is this not a backwards behaviour?

**Comment by DavidGamba** [comment]
Seems right to me, `enable_forced_updates` seems to mean that your existing runner will point to a configuration it wasn't spun up with which could lead to config drift.
The default behaviour should be the safe one `enable_forced_updates` set to false so a new ASG means a new runner without trying to force_update an existing one.

**Comment by martinhanzik** [comment]
Based on the documentation "Enable automatic redeployment of the Runner ASG when the Launch Configs change." I would expect, that setting it to `true` would redeploy the ASG with the new configuration, setting it to `false` would require me to manually update (by killing the old instance). It works exactly the opposite way.

Is `force_update` a term used with ASGs? Some kind of parameter to force it to redeploy all instances with the new launch configuration? I couldn't find any reference to this anywhere.

So either it's not named correctly, the documentation is wrong, or I'm just not understanding this.

**Comment by npalm** [comment]
@martinhanzik I fully agree to your comment. By setting `enable_forced_updates` to `false` should not impact the ASG en require manual intervetion. But I have just checked the configuration and it implmented in the opposite way. 

So the only good fix will be a breaking change with a new variable name. For the time being I can keep the old var as well. Do you have any suggestion for a new variable name? Most features that can be toggled starts with the prefix `enable`. So what do you think of `enable_asg_recreation`. Any better suggestion is welcome.

**Comment by martinhanzik** [comment]
`enable_asg_recreation` is probably the best, I haven't been able to come up with anything better.

**Comment by npalm** [comment]
@martinhanzik thx

**Comment by kayman-mk** [comment]
`enable_asg_recreation` is the correct choice. `enable_forced_updates` will be removed with #387

**Comment by kayman-mk** [comment]
@npalm Can be closed, right? Old variable was removed and the new one is in place.
