### ISSUE TITLE
Question: Use tls settings in [[runners]] section

### ISSUE THREAD

**Issue by nlarzon** [npalm/terraform-aws-gitlab-runner#227]
Hi,

I have a private gitlab that is requiring certificate to pass the firewall, so I need to be able to configure the following:
tls-cert-file | File containing the certificate to authenticate with the peer when using HTTPS
-- | --
tls-key-file | File containing the private key to authenticate with the peer when using HTTPS

https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runners-section

I have been looking into the possible variables configuration but it doesn't look like it is supported. 

I have been looking into adding it myself, but it is a bit complex withe all the use cases and configurations using the multiple templates files. Using the parameter store would be the preferred way? To support the autoscaling in the same way as for the token?

**Comment by npalm** [comment]
Thx for creating the issue, will come back to your question later this week.

**Comment by nlarzon** [comment]
We need to modify the 
```
token=$(aws ssm get-parameters --names "${secure_parameter_store_runner_token_key}" --with-decryption --region "${secure_parameter_store_region}" | jq -r ".Parameters | .[0] | .Value")
if [[ `echo ${runners_token}` == "__REPLACED_BY_USER_DATA__" && `echo $token` == "null" ]]
then
  token=$(curl --request POST -L "${runners_gitlab_url}/api/v4/runners" \
    --form "token=${gitlab_runner_registration_token}" \
    --form "tag_list=${gitlab_runner_tag_list}" \
    --form "description=${giltab_runner_description}" \
    --form "locked=${gitlab_runner_locked_to_project}" \
    --form "run_untagged=${gitlab_runner_run_untagged}" \
    --form "maximum_timeout=${gitlab_runner_maximum_timeout}" \
    --form "access_level=${gitlab_runner_access_level}" \
    | jq -r .token)
  aws ssm put-parameter --overwrite --type SecureString  --name "${secure_parameter_store_runner_token_key}" --value="$token" --region "${secure_parameter_store_region}"
fi
```
By adding :
```
--cert "/etc/gitlab_tls_cert.pem" --key "/etc/gitlab_tls_key.pem"
```

The question is what is the best way of getting the cert on to the machine?

**Comment by npalm** [comment]
A bit late response, but the best way is to user the user_data script to get it on the machine, You could copy the cert via SSM or S3 for example. 

You could add the follow line to the module:
```
  userdata_pre_install   = data.template_file.userdata.rendered
  docker_machine_options = ["amazonec2-userdata=/opt/gitlab-runner-config/user-data-dm.sh"]

```
And load the user data
```
data "template_file" "userdata" {
  template = file("./templates/userdata.tpl")
}
```
And create a template like:
```
mkdir -p /opt/gitlab-runner-config
tee /opt/gitlab-runner-config/user-data-dm.sh <<EOL
#!/bin/bash -ex

# your script

EOL
```
