### ISSUE TITLE
runner job when start stay freeze

### ISSUE THREAD

**Issue by fedemzcor** [npalm/terraform-aws-gitlab-runner#229]
May 28 16:53:59 ip-172-31-37-190 gitlab-runner[21306]: output  : sudo: docker: command not found         #033[0;m  driver#033[0;m=amazonec2 name#033[0;m=runner-faz2ny1r-runner-1590684391-01a082ca operation#033[0;m=create

May 28 16:54:03 ip-172-31-37-190 gitlab-runner[21306]: Error getting SSH command to check if the daemon is up: ssh command error:#033[0;m  driver#033[0;m=amazonec2 name#033[0;m=runner-faz2ny1r-runner-1590684391-01a082ca operation#033[0;m=create

**Comment by npalm** [comment]
@fedemzcor thanks for report but the information you provided does not ring any bell. We have no issues with the runners last months. We serve during day. time builds is roughly 10 docker machines.

**Comment by npalm** [comment]
@fedemzcor do you still have the issue?
