### ISSUE TITLE
Runner gets blacklisted for incorrect token

### ISSUE THREAD

**Issue by fliphess** [npalm/terraform-aws-gitlab-runner#231]
Hey Niek, 

I'm running into some issues when a agent node fails or when the agent is deleted and the machine is recreated withing the ASG from user-data.

I'm using the cloud version of gitlab, not a self hosted instance.

As soon as the gitlab-runner is installed, the runner is started with the token `__REPLACED_BY_USER_DATA__` and the next thing that happens is the gitlab runner trying to retrieve it's jobs with this token for several times, resulting in the runner being banned:

```
Jun 25 08:42:12 ip-XXXX.eu-central-1.compute.internal gitlab-runner[13168]: ERROR: Checking for jobs... forbidden               runner=XXXX
Jun 25 08:42:12 ip-XXXX.eu-central-1.compute.internal gitlab-runner[13168]: ERROR: Checking for jobs... forbidden               runner=XXXX
Jun 25 08:51:03 ip-XXXX.eu-central-1.compute.internal gitlab-runner[13168]: ERROR: Runner https://gitlab.com/XXXX is not healthy and will be disabled!
```

I've seen this issue before and was able to work around it by moving some tasks in user-data to the background to the token replace would be done quicker and as a result restarts before it does 2 or 3 requests to the gitlab api wih the incorrect token and being banned. 

This time I'm not able to work around it as it seems to be instant. Replacing the tokens in SSM or the configuration does not help, waiting for an hour or a day until the ban is lifted neither.

Have you seen this before and do you perhaps know how to work around it?

**Comment by fliphess** [comment]
I think this has something to do with it: 

```
 null_resource.remove_runner: Provisioning with 'local-exec'...
 null_resource.remove_runner (local-exec): Executing: ["/bin/sh" "-c" "./bin/remove-runner.sh eu-central-1 https://gitlab.com XXXX-runner-token"]
 null_resource.remove_runner (local-exec): ./bin/remove-runner.sh: 4: ./bin/remove-runner.sh: aws: not found
 null_resource.remove_runner (local-exec): {"message":"403 Forbidden"}
```

**Comment by fliphess** [comment]
I installed awscli in the container, now the local-exec succeeds but results in a SSM parameter value with value `null`

**Comment by npalm** [comment]
@fliphess thanks for sharing, will check your issue next week.

**Comment by fliphess** [comment]
What helped for me, was creating a new token, remove the SSM parameters and removing the instance so the ssm parameter is updated. 

I think there is a little timing issue that can work both ways: If you're lucky and the configuration is done fast enough the registration succeeds, if  there is a little slow down due to for example lots of packages having to be updated from user_data you can end up with a banned runner.

It might help to first set the correct token in the configuration toml prior to installing and starting the gitlab-runner service. I'm not sure if the configuration file is overwritten by the gitlab-runner installation.

I expect I'm able to work on this issue myself eventually: I'm a bit busy at the moment, but if it occurs on installations of other users of the module as well (if it's not just a ME-problem), I think I can create a workaround in a few weeks.

**Comment by npalm** [comment]
@fliphess would be great if you can come up with a proposal in the next week. I also quite busy. Maybe we could even completly remove the SSM storage.

**Comment by fliphess** [comment]
Hey @npalm 

To prevent secrets in git, I use secrets manager to store the tokens theirselves and let terraform retrieve them using a data source. This works well, but combined with SSM parameters it can cause some confusion om what places to change a token when a runner is blacklisted. 

The validation would help, but I'm not sure if it's needed if the SSM parameters are removed. The SSM parameter storage feels like an extra step that is not needed as the token is already in the terraform state anyway and can thus be provided solely through user_data. That way the token immediately updated when you change it (either in the module initiation or using helpers like secrets manager).

**Comment by fliphess** [comment]
I will close this issue: It's not relevant anymore as it has been working perfectly since a few releases ago: After 4.19.0 or 4.20.0 this issue has not appeared anymore.  👍

**Comment by strowi** [comment]
For future reference:
Since i ran into the same error message and it took me the better half of the day:
`gitlab_runner_registration_config["maximum_timeout"]` needs to be >= 10 minutes. (had a typo setting it to 300)
Found this error when debugging the registration curl-command.
