### ISSUE TITLE
Does aws_zone has to match the subnet availability zone?

### ISSUE THREAD

**Issue by kayma-hl** [npalm/terraform-aws-gitlab-runner#232]
Hi,

by accident I set the aws_zone to "b" but used a subnet_id_runners from availability zone eu-central-1a. As a result no runner was created. So if both variables are related I propose to remove the aws_zone variable and read the availability zone of the subnet via

`
data aws_subnet runners {
  id = var.subnet_id_runners
}
`

Best regards
Matthias Kay
Hapag-Lloyd AG

**Comment by npalm** [comment]
@kayma-hl I am not complete sure why we have splitted those two variables. I doubled checked the docker machine docs for EC2 (https://docs.docker.com/machine/drivers/aws/) and it seems we really have to set the zone paramters. Would you like to propose a PR to replace the logic by a lookup?
