### ISSUE TITLE
Merge tags for agent runner EC2 instance to remove duplicates

### ISSUE THREAD

**Issue by kayma-hl** [npalm/terraform-aws-gitlab-runner#233]
Hi,

I set the environment variable to "abc" and use tags for the runners including the name tag.

```
module "gitlab_terraform_runner" {
  ...
  environment                = "abc"
  agent_tags                 = merge(var.tags, map("Name", "Gitlab Runner Terraform Agent"))
  runner_tags                = merge(var.tags, map("Name", "Gitlab Runner Terraform"))
}
```

The problem is, that the environment variable is always added as a name tag to the agent. In the end it contains 2 name tags.

Proposal: Add the anvironment as name tag only if the agent has no name tag.

Best regards
Matthias Kay
Hapag-Lloyd AG

**Comment by npalm** [comment]
Good suggestion, could you propose a PR?

**Comment by kayma-hl** [comment]
The main problem was the creation of the tag list for the runner agent. It used local.tags which contained the "Name = var.environment" tag. When setting the tags of the instance a simple concat() of several lists was executed which resulted in two "Name" tags.

Replaced by another local variable "agent_tags" and used the merge() operation to remove the duplicate "Name" tag.
