### ISSUE TITLE
Pipeline is green but console shows error message

### ISSUE THREAD

**Issue by ghost** [npalm/terraform-aws-gitlab-runner#237]
A terraform file in a PR had an error, but all checks were passed?! The console output shows an error message.

See [Pipeline should fail](https://github.com/npalm/terraform-aws-gitlab-runner/pull/236/checks?check_run_id=840691206), step verify-examples.

**Comment by npalm** [comment]
Made some quick fixes in the pipelines. Try to find some time to refactory them based on hashicorp github action.

**Comment by kayman-mk** [comment]
Stupid me, the logs are gone. Closing the issue as it is not clear what was wrong. Had no problems in the last year with the pipeline.
