### ISSUE TITLE
Use runners.autoscaling instead of OffPeakPeriods

### ISSUE THREAD

**Issue by kayman-mk** [npalm/terraform-aws-gitlab-runner#240]
I received a warning that the Off Peak time mode shouldn't be used any longer (is deprecated) and should be replaced by [[runner.machine.autoscaling]]

```
[runners.machine]
OffPeakPeriods = [ 
  "* * 0-8,18-23 * * mon-fri *",
  "* * * * * sat,sun *" ]
```

**Comment by npalm** [comment]
@kayman-mk thanks for creating the issue.

**Comment by npalm** [comment]
Reference to docs: https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnersmachine-section

**Comment by npalm** [comment]
@kayman-mk I have create an implementation, needs to finish a bit of docs. Please feel free to have a look at PR #242
