### ISSUE TITLE
Help with runners_concurrent

### ISSUE THREAD

**Issue by ado120** [npalm/terraform-aws-gitlab-runner#248]
Hello! I am using the module and it is working great, just having some trouble understanding how it works..

I see that the default value for the runners_concurrent is 1, does this mean that only 1 pipeline can run at a time? On Kubernetes managed gitlab-runners the default value is 10. Any setback to setting it to a high number? If I have a pipeline that has multiple jobs in 1 stage, does that mean it will only go one at a time since the setting is default to 1?

**Comment by npalm** [comment]
I will close the issue, feel free to re-open if the answer was not helpful or clear
