### ISSUE TITLE
Add variable to disable detailed monitoring on the runner instance

### ISSUE THREAD

**Issue by jessedobbelaere** [npalm/terraform-aws-gitlab-runner#259]
I noticed there is a variable `runners_monitoring` (default: false) available which can enable/disable detailed Cloudwatch monitoring on the docker-machine instances. 

However, when checking the Terraform plan, the `module.runner.aws_autoscaling_group.gitlab_runner_instance` receives `EC2 detailed monitoring` enabled by default and I don't need detailed monitoring (not spinning up a critical stack for me). So I would like to disable that (for the cost).  

![image](https://user-images.githubusercontent.com/1352979/95268689-1e088e00-0838-11eb-8159-f488aa8be92a.png)

Seems like detailed monitoring (`enable_monitoring`) is enabled by default on `aws_launch_configuration`: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration

Is there any way to merge or override the `template_gitlab_runner` [locals of the module](https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/main.tf#L55-L75) in my own terraform code? Or should a variable be added to control detailed monitoring of the gitlab runner instance?

**Comment by npalm** [comment]
Seems monitoring is by default enabled in the auto launch configuration (https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_configuration#enable_monitoring). The auto scaling group is managing the gitlab agent, the runners are managed via docker machine and should have by default monitoring disabled. 

To disable monitoring for the instance running in the scaling group we have to create an extra variable. Feel free to propose a PR to introduce more flexibility in the module.
