### ISSUE TITLE
Gitlab runner for groups

### ISSUE THREAD

**Issue by ermiaqasemi** [npalm/terraform-aws-gitlab-runner#262]
Hi 

I wanna lunch the GitLab runner for my all the projects in the groups but when I add token group the runner does not appear on my runner list in GitLab but when adding project token it will be appear.

**Comment by ermiaqasemi** [comment]
I found the problem :D

**Comment by trallnag** [comment]
@ermiaqasemi could you share the solution / what the issue was?

**Comment by ermiaqasemi** [comment]
@trallnag Sure, in my case the issue was because of 2 reasons:

- I just figured out for setup runners at group level when you want to specify the gitlab URL project you must put a slash at the end of the URL otherwise it does not work.
- Also I forgot to allow internet connection for private instance at the routeing table in VPC setup.

After those are resolved everything works as expected.
