### ISSUE TITLE
Docker machine not launching properly in spot instances

### ISSUE THREAD

**Issue by augustorosa** [npalm/terraform-aws-gitlab-runner#264]
Hi, I used your modules and it all launches, well but when I target a build it does not build. it remains stuck on this "Preparing the "docker+machine" executor" and when i look logs, not much is there outside of this:
 

Nov  1 15:49:43 ip-172-20-112-240 gitlab-runner[12116]: Installing Docker...                              #033[0;m  driver#033[0;m=amazonec2 name#033[0;m=runner-wct6y7rn-runner-1604245704-f9f7037b operation#033[0;m=create | Nov   1 15:49:43 ip-172-20-112-240 gitlab-runner[12116]: Installing  Docker...                              #033[0;m   driver#033[0;m=amazonec2  name#033[0;m=runner-wct6y7rn-runner-1604245704-f9f7037b  operation#033[0;m=create
-- | --
 
Nov  1 15:50:01 ip-172-20-112-240 systemd: Created slice User Slice of root. 
and other like this,include a stop slice of root.

if I do remote the runner, and do a docker-machine ls, there no machines listed. so i can ssh into anything.
It seems that it did not deploy docker machine appropriately.

My config 

//gitlab-runner
data "aws_security_group" "default" {
  name   = "default"
  vpc_id = module.vpc-shared.vpc_id
}

module "cache" {
  source      = "../../modules/cache"
  environment = var.environment
}

module "key_pair" {
  source = "../../modules/key-pair"

  environment = var.environment
  name        = var.runner_name
}

module "runner" {
  source     = "../../modules/aws-gitlab-runner"

  aws_region = var.region
  environment = var.environment

  vpc_id                    = module.vpc-shared.vpc_id
  subnet_ids_gitlab_runner = module.public-subnets-shared.ids
  subnet_id_runners        = module.public-subnets-shared.ids[0]
  metrics_autoscaling      = ["GroupDesiredCapacity", "GroupInServiceCapacity"]

  runners_name             = var.runner_name
  runners_gitlab_url       = var.gitlab_url
  enable_runner_ssm_access = true

  gitlab_runner_security_group_ids = [data.aws_security_group.default.id]

  docker_machine_download_url   = "https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.2/docker-machine"
  docker_machine_spot_price_bid = "0.06"

  gitlab_runner_registration_config = {
    registration_token = var.registration_token
    tag_list           = "docker_spot_runner,aws"
    description        = "AWS runner - Spot"
    locked_to_project  = "true"
    run_untagged       = "false"
    maximum_timeout    = "3600"
  }

  tags = {
    "tf-aws-gitlab-runner:shared"           = "runner-default"
    "tf-aws-gitlab-runner:instancelifecycle" = "spot:yes"
  }

  runners_privileged         = "true"
  runners_additional_volumes = ["/certs/client"]

  runners_volumes_tmpfs = [
    {
      volume  = "/var/opt/cache",
      options = "rw,noexec"
    }
  ]

  runners_services_volumes_tmpfs = [
    {
      volume  = "/var/lib/mysql",
      options = "rw,noexec"
    }
  ]
  
  cache_shared = "true"

  cache_bucket = {
    create = false
    policy = "${module.cache.policy_arn}"
    bucket = "${module.cache.bucket}"
  }

  # working 9 to 5 :)
  # Deprecated, replaced by runners_machine_autoscaling
  # runners_off_peak_periods    = "[\"* * 0-9,17-23 * * mon-fri *\", \"* * * * * sat,sun *\"]"
  # runners_off_peak_timezone   = var.timezone
  # runners_off_peak_idle_count = 0
  # runners_off_peak_idle_time  = 60
  runners_machine_autoscaling = [
    {
      periods    = ["\"* * 0-9,17-23 * * mon-fri *\"", "\"* * * * * sat,sun *\""]
      idle_count = 0
      idle_time  = 60
      timezone   = var.timezone
    }
  ]
}

resource "null_resource" "cancel_spot_requests" {
  # Cancel active and open spot requests, terminate instances
  triggers = {
    environment = var.environment
  }

  provisioner "local-exec" {
    when    = destroy
    command = "../../modules/aws-gitlab-runner/ci/bin/cancel-spot-instances.sh ${self.triggers.environment}"
  }
}

Thank you so much for any help.

**Comment by npalm** [comment]
Hard to see what goes wrong. Could you give it a try with a vpc with public and private subnets, see default example.

**Comment by augustorosa** [comment]
Ok. yes that was the solution. It does not work with public subnets only private. Probably a good thing to say in your docs. and I want to tell you, THANK You, your module is amazing and very helpful. Have a great end of the year and keep healthy.

**Comment by augustorosa** [comment]
moved runners to private only subnets
