### ISSUE TITLE
Allow Docker Machine agent to have extensible policies

### ISSUE THREAD

**Issue by skang0601** [npalm/terraform-aws-gitlab-runner#267]
Rather than defining a policy attachment for the job instances after using declaring the module like so:

```
resource aws_iam_role_policy_attachment allow_ecr_full_agent {
  role       = module.gitlab_runner.runner_agent_role_name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
}

resource aws_iam_role_policy_attachment allow_ecr_full {
  role       = module.gitlab_runner.runner_role_name
  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
}
```

It would be more convenient for the module itself to accept a list of iam policies to attach to the docker machine role (especially for Terragrunt users)

**Comment by npalm** [comment]
@skang0601 would you like to propose the change in a PR. As long we can keep the module backwards compatible the sugesion sounds good to me

**Comment by skang0601** [comment]
@npalm CLosing this out looks like someone beat me to it on a PR :)
