### ISSUE TITLE
Install the docker-ecr-credential-helper

### ISSUE THREAD

**Issue by Fuuzetsu** [npalm/terraform-aws-gitlab-runner#271]
If we want to use docker-based executors and pull docker images from private ECR, we are likely to use https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#using-credential-helpers with DOCKER_AUTH_CONFIG set. To make use of this, the appropriate credential helper needs to be installed: https://github.com/awslabs/amazon-ecr-credential-helper

With current EC2 setup, this is just `yum install -y amazon-ecr-credential-helper`. The user can work-around this by using `userdata_post_install` variable but it'd be cool if there was a proper setting. It could even be on by default, there's not much reason (as far as I can tell) to not just install this by default.

**Comment by npalm** [comment]
Thanks, great suggestion!

**Comment by npalm** [comment]
solved via #311
