### ISSUE TITLE
Manage docker version on runner instance

### ISSUE THREAD

**Issue by vikassach** [npalm/terraform-aws-gitlab-runner#275]
Hi 
We are using this module for some time now but recently around a month ago runner instances updated docker versions from 19.03 to 20.10.1 and this is causing us some issues. I am trying to find if there is a config which can tell gitlab runner which docker version to install.
Following is the config that we are using:
```terraform
module "runner" {
  source  = "npalm/gitlab-runner/aws"
  version = "4.10.0"

  aws_region                      = "eu-west-1"
  environment                     = "on-demand-runners"
  enable_gitlab_runner_ssh_access = true
  docker_machine_instance_type    = "m5.xlarge"

  vpc_id                   = aws_vpc.gitlab.id
  subnet_ids_gitlab_runner = [aws_subnet.private_subnet_a.id, aws_subnet.private_subnet_b.id, aws_subnet.private_subnet_c.id, ]
  subnet_id_runners        = aws_subnet.private_subnet_a.id

  runners_name          = var.runners_name
  runners_gitlab_url    = var.runners_gitlab_url
  runners_concurrent    = 30
  runners_idle_time     = 3000

  ssh_key_pair = aws_key_pair.key.key_name

  gitlab_runner_registration_config = {
    run_untagged       = true
    registration_token = var.registration_token
    tag_list           = ""
    description        = ""
    locked_to_project  = ""
    maximum_timeout    = ""
  }

  runners_privileged         = "true"
  runners_additional_volumes = ["/var/run/docker.sock:/var/run/docker.sock", "/artifacts:/artifacts"]

  docker_machine_options = ["amazonec2-root-size=100"]
}
```
Thanks

**Comment by npalm** [comment]
At the moment the docker version of the runner agent is not configurable, docker is installed via a user data script, see https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/template/gitlab-runner.tpl  In your case it looks like your are using docker-machien and the docker version is provided via docker machine. Please feel free to suggest via an issue or PR any improvement that you have in mind.

**Comment by npalm** [comment]
Short update, we using sometimes dind to fix the version. Still having the issue?

**Comment by kayman-mk** [comment]
Could be nice to have an explicit docker version in the config or use the version proposed by the package manager.
