### ISSUE TITLE
'docker-machine: cannot execute binary file' error on startup

### ISSUE THREAD

**Issue by Glen-Moonpig** [npalm/terraform-aws-gitlab-runner#277]
Hello,

I have just updated to the latest release of the module (4.21.0), previously on 4.20.0.

The user data script is failing to execute to completion.
I think the script ends when it gets to [template/gitlab-runner.tpl#L39](https://github.com/npalm/terraform-aws-gitlab-runner/blob/2ccd3d8d6b5cb609c32c98d7b262c1530d638401/template/gitlab-runner.tpl#L39).

The log shows:

```
user-data: + curl --fail --retry 6 -L https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.10/docker-machine-Linux-aarch64
user-data: % Total % Received % Xferd Average Speed Time Time Time Current
user-data: Dload Upload Total Spent Left Speed
user-data: #015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0#015 14 41.5M   14 6223k    0     0  5039k      0  0:00:08  0:00:01  0:00:07 5035k#015 61 41.5M   61 25.5M    0     0  11.5M      0  0:00:03  0:00:02  0:00:01 11.5M#015100 41.5M  100 41.5M    0     0  14.0M      0  0:00:02  0:00:02 --:--:-- 14.0M
user-data: + chmod +x /tmp/docker-machine
user-data: + mv /tmp/docker-machine /usr/local/bin/docker-machine
user-data: + ln -s /usr/local/bin/docker-machine /usr/bin/docker-machine
user-data: + docker-machine --version
user-data: /var/lib/cloud/instance/scripts/part-001: line 182: /usr/local/bin/docker-machine: cannot execute binary file
cloud-init: Jan 18 16:34:37 cloud-init[2399]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [126]
cloud-init: Jan 18 16:34:37 cloud-init[2399]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
cloud-init[2399]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
cloud-init: ci-info: no authorized ssh keys fingerprints found for user ec2-user.
```

I have been looking at this a while and not sure what to try to fix it. Do you have any idea what the problem could be?

**Comment by Glen-Moonpig** [comment]
I expect the docker-machine version is not compatible with the runner type as it appears to be compiled for ARM. How can I find a listing of docker-machine download URL's?

**Comment by Glen-Moonpig** [comment]
Found a listing of docker-machine builds [here](https://gitlab-docker-machine-downloads.s3.amazonaws.com/master/index.html).

Added an input to the **terraform-aws-gitlab-runner** module
```
docker_machine_download_url = "https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.10/docker-machine-Linux-x86_64"
```

It now works with my instance types.

**Comment by npalm** [comment]
I have updated the defaults to the gitlab matained one. This since this version is still maintained. Did not checkec impact for other architectures then the one in the default example.

**Comment by JulianCBC** [comment]
The issue here is that the default runner agent machine type is a `t3.micro` x86 VM, but the docker-machine version in the defaults is an AArch64 one, hence this falling over if you "just" update without reading and understanding the changes made.

I guess that the default for one of these needs to be changed: either update the `t3.micro` default to an equivalent AArch64 machine type or update the default docker machine url to the x86 version.

To be honest, as the AArch64 VMs are (supposed to be) cheaper than the x86 ones and it's the new hotness, maybe it's time to update the default machine type for the runner agent?

**Comment by Nightbr** [comment]
Hey same here with latest version `4.22.0` + `Gitlab runner 13.8.0` from a fresh setup.
The runner was not autoRegister (failed initScript) but the machine `t3.micro` was still running with green lights (on AWS).

Added  ` docker_machine_download_url = "https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.10/docker-machine-Linux-x86_64"` to my module config and it works now.

Perhpas it could be great to put it as default or like @JulianCBC suggests update the default machine type for the runner agent.

We could reopen this maybe.
