### ISSUE TITLE
Cannot set multiline build scripts

### ISSUE THREAD

**Issue by fpalluel** [npalm/terraform-aws-gitlab-runner#281]
Hello,
We are facing a problem when trying to set a multiline `pre_build_script`.

The generated `config.toml` is:

```
pre_build_script="'''
echo 'line 1'
echo 'line 2'
'''"
```
whereas it should be:

```
pre_build_script='''
echo 'line 1'
echo 'line 2'
'''
```

The problem lies in `runner-config.tpl`, where `*_build_script` declarations are enclosed in double quotes:
```
 pre_build_script = "${runners_pre_build_script}"
 post_build_script = "${runners_post_build_script}"
 pre_clone_script = "${runners_pre_clone_script}"
```

Do you think it is sensible to remove them, to allow both single and multilines scripts ?
I can make a PR if you think it is ;-)

**Comment by npalm** [comment]
Feel free to make a PR, can you also add a simple script (pre or post for example with some echo statements) to the default example

**Comment by fpalluel** [comment]
Done ;-)

**Comment by npalm** [comment]
closing, since it is solved
