### ISSUE TITLE
Problem using the shared cache solution with multiple runners (Invalid count argument)

### ISSUE THREAD

**Issue by stefan-kolb** [npalm/terraform-aws-gitlab-runner#298]
I'm trying to use a shared bucket (as in the examples) together with multiple runners created via `for_each` (not sure if this issue is also relevant without it but I guess so).

```
module "cache" {
  source  = "npalm/gitlab-runner/aws//modules/cache"
  version = "4.21.0"
  environment = "gitlab-runner"
}

module "runner" {
  source  = "npalm/gitlab-runner/aws"
  version = "4.21.0"

  # module will be created for every key in this map
  for_each = var.runners

  # network settings
  aws_region = var.aws_region
  vpc_id     = var.vpc_id
  subnet_ids_gitlab_runner = [var.subnet_id]
  subnet_id_runners        = var.subnet_id
  metrics_autoscaling      = ["GroupDesiredCapacity", "GroupInServiceCapacity"]

  # instance configuration
  environment              = each.key
  instance_type            = each.value.instance_type

(...)

  gitlab_runner_security_group_ids = [var.security_group_id]

  gitlab_runner_registration_config = {
    registration_token = var.registration_token_map[each.value.registration_token_key]
    tag_list           = each.value.tags
    description        = each.value.runner_name
    locked_to_project  = "true"
    run_untagged       = "false"
    maximum_timeout    = "3600"
  }

  cache_shared = "true"

  cache_bucket = {
    create = false
    policy = module.cache.policy_arn
    bucket = module.cache.bucket
  }

  }
```

Applying this configuration results in an error: 
```
Error: Invalid count argument

  on ..\..\..\terraform-aws-gitlab-runner\main.tf line 323, in resource "aws_iam_role_policy_attachment" "docker_machine_cache_instance":
 323:   count      = var.cache_bucket["create"] || local.bucket_policy != "" ? 1 : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.

```

Applying this config is only possible via:
`terraform plan -target=module.cache` first followed by a second `terraform apply`, because `lookup(var.cache_bucket, "policy", "")` is used inside module which is only available after creating the bucket.

```
resource "aws_iam_role_policy_attachment" "docker_machine_cache_instance" {
  count      = var.cache_bucket["create"] || lookup(var.cache_bucket, "policy", "") != "" ? 1 : 0
  role       = aws_iam_role.instance.name
  policy_arn = local.bucket_policy
}
```

See https://github.com/terraform-aws-modules/terraform-aws-transit-gateway/issues/2
See https://github.com/hashicorp/terraform/issues/4149

```
$ terraform init
$ terraform plan -target module.cache
$ terraform apply -target module.cache
$ terraform plan
$ terraform apply
```

The question here is, can we solve this issue somehow?
Do we really need `count      = var.cache_bucket["create"] || lookup(var.cache_bucket, "policy", "") != "" ? 1 : 0` here? Is there a use case where we do not want to add the policy at all? If not, we could ommit the count and solve the problem entirely and make it easier for users?

@npalm WDYT?

**Comment by vgropp** [comment]
this issue also exists without `for_each`

**Comment by fliphess** [comment]
You can work around it by creating the cache first and the runners after it.

**Comment by vgropp** [comment]
yes, that does work, but we had a non shared cache with a runner module and tried to introduce a second runner with a shared cache for both, so we had to remove the old runner with non shared cache

**Comment by dsalaza4** [comment]
This is still affecting reproducibility for the module :face_with_head_bandage:

**Comment by kayman-mk** [comment]
Do not add the policy means not having access to a cache. I will never have that. Any other ideas? Are there use cases for the runner without having a cache?
