### ISSUE TITLE
docker machine defaults to aarch64, best to make to autodetect?

### ISSUE THREAD

**Issue by rtoma** [npalm/terraform-aws-gitlab-runner#299]
Wondering why the default `docker_machine_download_url` defaults to the aarch64 binary. Note the description mentions x64.

```
variable "docker_machine_download_url" {
  description = "Full url pointing to a linux x64 distribution of docker machine. Once set `docker_machine_version` will be ingored. For example the GitLab version, https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.2/docker-machine."
  type        = string
  default     = "https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.10/docker-machine-Linux-aarch64"
}
```

Maybe best to default `docker_machine_download_url` to `""` and add a default `docker_machine_version` value? That way the `template/gitlab-runner.tpl` will download the appropriate arch and code will work for more users. Thanks!

**Comment by npalm** [comment]
The default should point to the x64 versions, since the default is also m5.arge

**Comment by npalm** [comment]
I configure it always expicit like https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/examples/runner-default/main.tf so completely missed the bug

**Comment by npalm** [comment]
I will set the default URL to `https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.2/docker-machine` So it supports the default settings
