### ISSUE TITLE
Question: Where are the docker+machine executor EC2 instances configured?

### ISSUE THREAD

**Issue by trallnag** [npalm/terraform-aws-gitlab-runner#302]
I'm trying to understand the code base because I want to try to refactor / add a feature to manage multiple GitLab runner agents with ECS. I understand how and where the runner agent is configured. This also includes stuff like installing the SSM agent or setting up logging in the EC2 instances.

But what about the instances started and managed by Docker Machine? From what I understand vanilla Amazon Linux 2 AMIs are used and beyond that no additional configuration. Am I correct or missing something?

**Comment by rtoma** [comment]
See the `MachineOptions` array in the `[runners.machine]` section in https://github.com/npalm/terraform-aws-gitlab-runner/blob/8335e53fabfcd8f488c69441dc6b4dc1d9e4a642/template/runner-config.tpl#L38 - this includes the AMI, instance type, region, az, vpc id etc of the runners.

**Comment by trallnag** [comment]
Alright thanks. So Docker Machine configures everything and there's no additional user data or so involved
