### ISSUE TITLE
Missing documentation makes setup fail

### ISSUE THREAD

**Issue by erback** [npalm/terraform-aws-gitlab-runner#31]
Just spent the better part of a day trying to setup the runner via this module without success. After some digging around I realized that there are some settings that are necessary but not provided in the documentation (but exist in the  example folder): 
```
  runners_off_peak_periods = "[\"* * 0-9,17-23 * * mon-fri *\", \"* * * * * sat,sun *\"]" 
```
If runners_off_peak_periods value is not set the setup script will fail due to empty variable. This either need to be a required variable or a default value needs to be set.

Thanks for a great module, apart from this little failure it works like a charm!

**Comment by msvechla** [comment]
Correct, I also noticed this a couple of weeks ago, but forgot to create an issue.

**Comment by npalm** [comment]
Thanks, will update the docs

**Comment by npalm** [comment]
Mode the variable optional
