### ISSUE TITLE
Tags not being applied on somes resources

### ISSUE THREAD

**Issue by florian0410** [npalm/terraform-aws-gitlab-runner#315]
Hello, I realized that some resources created by this module are not tagged using the tags variable, I'm listing these here:

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L260-L263

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L341-L344

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L274-L280

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L290-L298

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L366-L374

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L390-L398

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L410-L418

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L265-L269

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/main.tf#L335-L339

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/logging.tf#L1-L6

https://github.com/npalm/terraform-aws-gitlab-runner/blob/8b15241b34c87d7b21c7a14fddf7d0b84f750f1b/modules/cache/main.tf#L76-L88

**Comment by npalm** [comment]
Thanks for reporting

**Comment by npalm** [comment]
- tags not supported for aws_iam_role_policy since this only create a inlince policy for the role
- Requires upgrade to aws provider 3.35

**Comment by florian0410** [comment]
Tested on my side.

Sounds good to me. Thanks !
