### ISSUE TITLE
Spot instances over multiple AWS Availability Zones

### ISSUE THREAD

**Issue by guillemtp** [npalm/terraform-aws-gitlab-runner#322]
Hi!

Is there any option to configure the same GitLab Runner agent to use multiple AWS AZ on spot instances?

Thanks

**Comment by npalm** [comment]
Yes, just provide a subnet for each zone, instances should be started (guess random) over your zones.

**Comment by guillemtp** [comment]
In which module attribute should be defined?

The attribute `subnet_id_runners` is only for one subnet.

**Comment by pierlucg-xs** [comment]
I don't think this is possible at the moment: https://docs.gitlab.com/runner/configuration/runner_autoscale_aws/#:~:text=If%20not%20specified%2C%20the%20availability%20zone%20is%20a%2C%20it%20needs%20to%20be%20set%20to%20the%20same%20availability%20zone%20as%20the%20specified%20subnet%2C%20for%20example%20when%20the%20zone%20is%20eu-west-1b%20it%20has%20to%20be%20amazonec2-zone%3Db

**Comment by kayman-mk** [comment]
As a workaround you could spin up agents in different AZs. It's almost the same.

**Comment by npalm** [comment]
Also having 2 deployments
