### ISSUE TITLE
Package name for gitlab has changed

### ISSUE THREAD

**Issue by weslarkit** [npalm/terraform-aws-gitlab-runner#329]
`curl --fail --retry 6 -L https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh | bash yum install gitlab-runner-${gitlab_runner_version} -y`

The above name gitlab-runner-XXX is not valid running with Amazon Linux as the package is named gitlab-runner.x86_64

**Comment by nikola197** [comment]
GitLab resolved package name issue.

**Comment by npalm** [comment]
So we can close the issue?

**Comment by weslarkit** [comment]
Definitely, feel free to close and thank you
