### ISSUE TITLE
Terraform version 1.0 support

### ISSUE THREAD

**Issue by r33drichards** [npalm/terraform-aws-gitlab-runner#330]
https://www.hashicorp.com/blog/announcing-hashicorp-terraform-1-0-general-availability

terraform version 1.0 has been announced. Would be great if this project could support it. I should be available next month to contribute changes so creating and issue here to centralize info related and stuff that should be done.

**Comment by kayman-mk** [comment]
Could you please give some more details here? At least the plan was generated with Terraform 1.0

**Comment by npalm** [comment]
For some reason CI jobs seems also failing for 1.x
