### ISSUE TITLE
Increase size of EBS on Docker Machine

### ISSUE THREAD

**Issue by cmbailey87** [npalm/terraform-aws-gitlab-runner#345]
Hey all, search through the docs and found where I can increase the size of the gitlab runner, but I need to increase the size of the EBS on the docker machines. It looks like it currently defaults to 16GB and I would like to go beyond that level. 
I wasnt able to locate any information on this in the documentation.
An information you can provide will be insightful
thanks

**Comment by kayman-mk** [comment]
There is a docker_machine_option you can use when creating the module: `docker_machine_options           = ["amazonec2-root-size=32"]`

**Comment by cmbailey87** [comment]
> There is a docker_machine_option you can use when creating the module: `docker_machine_options = ["amazonec2-root-size=16"]`

is there any documentation that details on the available options under the docker_machine_options that you can point me to?
thanks in advance.

**Comment by kayman-mk** [comment]
Check out https://docs.docker.com/machine/drivers/aws/

**Comment by npalm** [comment]
assume issue is resolved, closing
