### ISSUE TITLE
Add ability to specify availability zone

### ISSUE THREAD

**Issue by declension** [npalm/terraform-aws-gitlab-runner#35]
Hi. First of all, thanks for a great module (and blog post). Cool stuff.

### Background
I've been setting it up here for a self-hosted, locked down Gitlab server. After getting the (organisation) region, VPC and subnet fixed for $WORK (but using `data` at least), the runner is green.

### Problem
However it is failing with 
```
Error creating machine: Error in driver during machine creation: Error request spot instance: 
InvalidParameterValue: Value (us-east-2a) for parameter availabilityZone is invalid. 
Subnet 'subnet-****************' is in the availability zone us-east-2c
```
Clearly I guess the subnet we've been given is in `us-east-2c` AZ but at no point can I seem to specify this, as [the template seems not to have this `MachineOption`](https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/template/runner-config.tpl#L35).

I guess the [example always creates the subnet in zone `a`](https://github.com/npalm/terraform-aws-gitlab-runner/blob/master/examples/runner-default/main.tf#L8) too, so maybe this is why it's never much of an issue.

### Proposed improvement
It would be good to have another variable for `aws_availability_zone` or similar.

### Workaround
Use `docker_machine_options`, I'm guessing?

**Comment by declension** [comment]
Update: `docker_machine_options` works :slightly_smiling_face: -  though not how [the comment says](https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/variables.tf#L237):
``` 
E.g. '[\"--amazonec2-zone=a\"]' 
```
That makes the fail to start, with CLI errors about `----amazonec2-zone` not being understood.
Removing the leading `--` fixes everything.

I'll make a separate PR for that perhaps?

**Comment by npalm** [comment]
Thanks for creating the issue. Feel free to create a PR for your proposal.
