### ISSUE TITLE
How to forward Gitlab CI/CD env vars to the Gitlab spot runners? 

### ISSUE THREAD

**Issue by akdj** [npalm/terraform-aws-gitlab-runner#364]
How to forward Gitlab CI/CD env vars to the Gitlab spot runners? 

When I run a pipeline, I saw that there are some throw errors about my Gitlab CI/CD env vars that are empties. 

Could you please help me? Is there an option that should I enable for forwards them?

**Comment by akdj** [comment]
Is there anybody?

**Comment by kayman-mk** [comment]
There is nothing special with spot/non spot instances. All Gitlab CI/CD environment variables are available for all type of runners. Could you share some log files and job outputs?

**Comment by npalm** [comment]
Looks like the issue resolved, can we close the issue?

**Comment by akdj** [comment]
Hi, I didn’t resolve the issue. But yes, we can close it. I will reopen when I will rework on it
