### ISSUE TITLE
how to ssh on gitlab runner EC2 machine?

### ISSUE THREAD

**Issue by akdj** [npalm/terraform-aws-gitlab-runner#365]
I don't know why, I cannot ssh on the machine with a key that I pre-generated and stored on AWS. 
I used the   `ssh_key_pair = var.my_key_name` when building the gitlab runner machine.

**Comment by akdj** [comment]
Is there anybody?

**Comment by kayman-mk** [comment]
Have you tried the SSM feature? Select the machine in the AWS Console and click connect. We dropped the SSH support on our runners.

**Comment by npalm** [comment]
We also use SSM if needed

**Comment by npalm** [comment]
I have to dive in this topic in detail. From the top of my head the runner supports
- provide you own key
- generate a key for you (if still supported, this should be dropped in my opinion)
- SSM, should by default choice, and disabled by default. The default should be no access at all.
