### ISSUE TITLE
S3 cache BucketLocation

### ISSUE THREAD

**Issue by welderpb** [npalm/terraform-aws-gitlab-runner#367]
Hello,

i have gitlab runner in one region region. And i have S3 bucket with cache in another region..
How can i specify BucketLocation region?
it is always overwriting with region of gitlab runner..

Thank you.

**Comment by kayman-mk** [comment]
That's not possible at the moment as we are using one provider only.

Could you elaborate on why it makes sense to put the cache in another region? Should be faster to use the same region, I think.

**Comment by kayman-mk** [comment]
@welderpb Is this still an issue?

**Comment by welderpb** [comment]
@kayman-mk it is not issue, it is feature request.. It would be great, if i can specify BucketLocation for s3 bucket..

**Comment by kayman-mk** [comment]
Ah, I see. What is the business reason behind? I usually create the cache in the same region the Runner/Executors are created in. Anything I can add to the PR?

**Comment by kayman-mk** [comment]
There seems to be no use case. Closing.
