### ISSUE TITLE
Severe security vulnerability scanned by ScoutSuite on runner agent policy

### ISSUE THREAD

**Issue by narenaryan** [npalm/terraform-aws-gitlab-runner#368]
Hi,

We are using `terraform-aws-gitlab-runnner` to spin up GitLab runners on our AWS account. As part of security auditing, there was a severe alert raised on this policy created by terraform module: https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/policies/instance-docker-machine-policy.json#L21

The problem lies with permitting `IamPassrole` action on all resources. As per Access Advisor [AWS](https://aws.amazon.com/blogs/security/identify-unused-iam-roles-remove-confidently-last-used-timestamp/), we can confirm that this action is not being used at all.

Therefore, can we remove this action from the policy to make the infrastructure more secure? If you think it should be fine, can I give a PR for that?

**Comment by kayman-mk** [comment]
Have you tried to remove this action and see what happens?

**Comment by narenaryan** [comment]
@kayman-mk, functionality-wise, nothing happened on our side. Let us confirm from your run.

**Comment by kayman-mk** [comment]
I'd like to try it again on monday as I updated to 4.30.0 and removed the IamPassRole. I had some troubles with the agents not being able to create the runners. Might they need this policy to pass the role to the runner (not 100% sure what this policy is good for)?

**Comment by npalm** [comment]
From the top of my head the IAM pass role is required on the agent instance to pass the role to the docker machine instances.

**Comment by kayman-mk** [comment]
Niek, I think so too. Had some problems to get the runners started without the iam:PassRole policy.

**Comment by narenaryan** [comment]
Hi @npalm, sorry for the delay, I am on vacation now. I will pass this to my team to get the role re-scanned.

**Comment by kayman-mk** [comment]
@narenaryan Any news here?

**Comment by kayman-mk** [comment]
@narenaryan Any news here or can the issue be closed?

**Comment by npalm** [comment]
I won't be close to my laptop the next weeks, so no updates from me

**Comment by kayman-mk** [comment]
Closed due to missing feedback. Should have been fixed some months ago.

Please reopen the issue if still valid.
