### ISSUE TITLE
Unable to remove runner when assuming role

### ISSUE THREAD

**Issue by ryancausey** [npalm/terraform-aws-gitlab-runner#371]
Currently, when using an [assume role configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#assume-role) on the AWS provider, this module cannot unregister the runner due to the remove-runner.sh script not assuming the same role assumed by the AWS provider. This leads to the AWS CLI call using the wrong role to try to pull the token value from the SSM parameter store.

I think a potential solution would be to use the [ssm parameter data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/ssm_parameter) to read the value using the role assumed by the provider, and then pass the token to the script. This would be done instead of having the script use the AWS CLI to pull the value from the SSM parameter store itself.

Since the script uses the AWS CLI, the current workaround is to configure a shared credentials file in ~/.aws/credentials and have an ~/.aws/config file with a configuration set to assume the role using the credentials from the shared credentials file like so:

```
# ~/.aws/credentials
[default]
aws_access_key_id=<your key ID>
aws_secret_access_key=<your secret key>

# ~/.aws/config
[default]
role_arn=<ARN of role assumed by the AWS provider>
source_profile=default
role_session_name=<session name you want to use>
region=<same AWS region the AWS provider is configured to use>
```

**Comment by kayman-mk** [comment]
I think so too. As the script is quite easy we could try to use the [fmontezuma/restapi](https://registry.terraform.io/providers/fmontezuma/restapi/latest/docs) provider.

**Comment by npalm** [comment]
Yes PR looks ready, @kayman-mk please can you remove the draft state once ready.
