### ISSUE TITLE
Add ability to specify runner tags

### ISSUE THREAD

**Issue by declension** [npalm/terraform-aws-gitlab-runner#39]
### Background
Currently, the tags for _runners_ (not the bastion) are hard-coded to:
```
amazonec2-tags=environment,${environment}
```
(see [current runner-config.tpl](https://github.com/npalm/terraform-aws-gitlab-runner/blob/6cde4994e4cbeb979da8f9853bc7a3372538bd7f/template/runner-config.tpl#L45))

### Proposal

- It'd be good if users could specify their own / extra tags for runners.
- Perhaps the current `environment` could  just be a _default_ key/value pair, meaning users could _override_ existing ones too (for example, we usually use `Environment` (capitalised)).

**Comment by npalm** [comment]
@declension Yes good idea. Currently it is possible to pass a of tags, in the file `tags.tf` they are merged together with `environment`. Problem is only that docker machine expects a flat comma separated string. Do you know how convert the map back to the String. Would be great to have it backwards compatible.

**Comment by npalm** [comment]
Answer to myself ;) ```"${replace(jsonencode(local.tags), "/[\\{\\}\"\\s]/", "")}"```

**Comment by declension** [comment]
Wow - speedy! Thanks @npalm I look forward to trying this out
