### ISSUE TITLE
Add a cost estimation for this module

### ISSUE THREAD

**Issue by kayman-mk** [npalm/terraform-aws-gitlab-runner#394]
Idea: To get an overview about the costs for typical setups. Add the details of the setup to the README.md

I will add an example for Hapag-Lloyd:

- number of developers using the Gitlab Runner
- number of instances min/max
- idle time
- working hours
- costs per business day

I guess other companies are using this module as well? Philips? Libri?

**Comment by kayman-mk** [comment]
@npalm @PirminTapken Any chance that you can also add some cost insights?

**Comment by npalm** [comment]
It is quite hard, costs are depend on type of load and type of instance. So sharing does not much so much sense. We are able to handle roughly 10K jobs a month with max 10 runners of a medium type

**Comment by kayman-mk** [comment]
Yeah I know. But for Newcomers it's always hard to guess the costs. So I took our costs of one week divided by 7 and added some details about the setup.
