### ISSUE TITLE
Occasionally EC2s are left in a Stopped state

### ISSUE THREAD

**Issue by cmavromichalis** [npalm/terraform-aws-gitlab-runner#398]
I've noticed that as I update the GitLab runner versions occasionally there are EC2's in a Stopped state. I have to manually delete these when running the terraform as the terraform won't destroy EC2's in a Stopped state. I haven't been able to root cause why they are put in a stopped state or any kind of pattern for why. It seems to just happen randomly and infrequently.

My scenario is the GitLab CI docker-machine runner - one runner agent as described in the README. We update GitLab and GitLab runner's versions once a month. Sometime during the month of use the EC2 is started then put in a Stopped state.

Are there logs I could look at or provide to help root cause this?

**Comment by kayman-mk** [comment]
I didn't find any special settings in my configuration. Do you have log files available?

**Comment by cmavromichalis** [comment]
I have looked through the EC2 logs but havent found anything that jumped out at me. Are there specific logs that would help?

**Comment by npalm** [comment]
We also didn't see this behaviour

**Comment by kayman-mk** [comment]
This will be indirectly solved by #392

**Comment by kayman-mk** [comment]
@cmavromichalis Shouldn't be an issue anymore and can be closed right?
