### ISSUE TITLE
Harmonize the wording for Runner and Executor

### ISSUE THREAD

**Issue by kayman-mk** [npalm/terraform-aws-gitlab-runner#405]
Sometimes the Runner is named "agent" or "coordinator" and the Executor appears as "worker" or "runner instance". According to the [Gitlab documentation](https://docs.gitlab.com/runner/) we have Runner and Executors only.

We should harmonize the wording in all files to adhere to the official wording to avoid misunderstandings.

**Comment by kayman-mk** [comment]
@npalm There are so many variables dealing with the runner and others dealing with the executor. It might be better to create a map of them to clean the configuration:
```hcl
module "gitlab_runner" {
  runner {
    iam_policy_arns = ["some", "ARNs"]
    security_group_ids = ["id1", id2"]
  }

  executors {
    post_build_script = "abc.sh"
    root_size = 16
  }
}
```

**Comment by npalm** [comment]
@kayman-mk agree but as you can understand it is grown over time (5 years or so). The idea is to provide reasonable defaults but give users the option to fine tune. Also I took great care of keeping the module as much as possible backwards compatible, refactoring to objects or maps will give most likely users some hard time to upgrade.

For other modules I also had a look on this approach, but what I don't like is that Terraform does not provide a goed way of documenting structures in a variable. So yes I agree the variable is a huge list, and yes wording could be done a bit better. But moving to a map and lossing the option toe describe variables is really a down side for me.

**Comment by kayman-mk** [comment]
Yeap, that is really a problem in Terraform.
