### ISSUE TITLE
Cache policy attached to runner instead of docker machine instance

### ISSUE THREAD

**Issue by hntrmrrs** [npalm/terraform-aws-gitlab-runner#409]
https://github.com/npalm/terraform-aws-gitlab-runner/blob/3ea16b04df7129c813f46cdcbf42aba3da90e65a/main.tf#L406

If docker machine runners are used, I believe this should be attached to the docker machine instance role instead.

**Comment by kayman-mk** [comment]
@hntrmrrs I think this issue is done as explained in #410. Could you please close it?
