### ISSUE TITLE
amazonec2-iam-instance-profile missing

### ISSUE THREAD

**Issue by msvechla** [npalm/terraform-aws-gitlab-runner#41]
Hello, 

it looks like since version 2.1.0 the option `amazonec2-iam-instance-profile` is missing.
Looks like this was removed by accident when resolving merge conflicts.

The diff is here:
https://github.com/npalm/terraform-aws-gitlab-runner/compare/2.0.0...2.1.0#diff-037af380e1e9a26cfbcaa481f820aacbL42

Could you add the missing option again?

**Comment by msvechla** [comment]
created PR: https://github.com/npalm/terraform-aws-gitlab-runner/pull/42/

**Comment by npalm** [comment]
@msvechla thanks for the notice and PR, but the PR wasn't working. A instance profile for the docker machine spot instances was missing. I have added a basic profile. 

I was also expecting this profile can be used to access the s3 cache by the runner. But it seems that this have to be in the profile of the instance. 

I have added my changes to your PR, is now in a branch on this repo. Please can you have a look? Is this working for you?
https://github.com/npalm/terraform-aws-gitlab-runner/tree/msvechla-fix-iam-instance-role

**Comment by msvechla** [comment]
thanks, looks fine but we should output the `${aws_iam_role.docker_machine.name}`, so it can be customized / extended. Otherwise it looks fine.

**Comment by npalm** [comment]
Yepz, of course :) Will added later this week.
