### ISSUE TITLE
Can not assign subnets during execution "terraform plan"

### ISSUE THREAD

**Issue by kostyanius** [npalm/terraform-aws-gitlab-runner#411]
Error: Variables not allowed
│
│   on <value for var.subnet_ids_gitlab_runner> line 1:
│   (source code not available)
│
│ Variables may not be used here.
╵
╷
│ Error: No value for required variable
│
│   on variables.tf line 27:
│   27: variable "subnet_ids_gitlab_runner" {
│
│ The root module input variable "subnet_ids_gitlab_runner" is not set, and has no default value. Use a -var or
│ -var-file command line argument to provide a value for this variable.

if to hardcode the value in the variables.tf than error changes to the following:

│ Error: Variables not allowed
│
│   on <value for var.subnet_ids_gitlab_runner> line 1:
│   (source code not available)
│
│ Variables may not be used here.
╵
╷
│ Error: No value for required variable
│
│   on variables.tf line 28:
│   28: variable "subnet_ids_gitlab_runner" {
│
│ The root module input variable "subnet_ids_gitlab_runner" is not set, and has no default value. Use a -var or
│ -var-file command line argument to provide a value for this variable.
╵

**Comment by npalm** [comment]
Are you using one of the examples?

**Comment by kostyanius** [comment]
i tried to do it from scratch and also checked examples. both cases do not work fro me. so looks like there is an issue with subnets.

**Comment by kayman-mk** [comment]
Do you have step by step instructions to reproduce the problem? Like: `git clone something && run something`? Hard to say what's going wrong without seeing your console.

**Comment by npalm** [comment]
@kostyanius still having the issues. Our deployment relies also on predefined subnets and we having no issues.

**Comment by kostyanius** [comment]
Hello folks. 
Thanks for your updates. I will record the video tomorrow for you all to show the issue i am facing with during this setup. Sorry for delay in my response. Was busy.

**Comment by kostyanius** [comment]
![image](https://user-images.githubusercontent.com/9063908/145838110-e9bcab72-230d-41ae-a12e-710fd022da56.png)

**Comment by kostyanius** [comment]
Hey
Any updates on this?
Thanks.

**Comment by kayman-mk** [comment]
@kostyanius Variable names can be improved, yes.

```hcl
variable "subnet_id_runners" {
  description = "List of subnets used for hosting the gitlab-runners."
  type        = string
}

variable "subnet_ids_gitlab_runner" {
  description = "Subnet used for hosting the GitLab runner."
  type        = list(string)
}
```

So the `subnet_id_runners` is a single subnet, no list. `subnet_ids_gitlab_runner` is a list of subnets.

**Comment by kostyanius** [comment]
Thanks but it is excess configuration anyway and in my case does not work for one subnet or for many of them. Why do we need such duplicate subnet or subnets? Only one of them is enough i believe. 
I have tried all the examples and only managed to run it for the new vpc and subnet. But it does not work for the existing vpc and subnets.

**Comment by kayman-mk** [comment]
Good point. And looking at my configuration I am using the same subnet for both, thus making sure that the runner agent (manager) is placed in the same subnet as the the runners (workers). Anything else doesn't make sense from my point of view.

You definitely have to provide both. As far as I can see, `subnet_ids_gitlab_runner` refers to the agent and `subnet_id_runners` to the workers.

It does work for existing VPCs and subnets. May be the `aws_region`, `vpc_id`, `subnet_ids_gitlab_runners` and `subnet_id_runners` are from different VPCs? Any subtle error or so?

**Comment by kostyanius** [comment]
Hello @kayman-mk 
No, aws region, vpn and subnets are correct. 
Subnets corresponds with vpc and vice versa. 
I even tried to type vpn and subnets name but got the same issue as for typing vpc and subnets id. 
I even tried to run it with sudo, but it didn`t help.
So, still do not know where is an issue may be. (
![image](https://user-images.githubusercontent.com/9063908/147925129-75895d1d-7445-415a-af0b-72f89eaec232.png)

**Comment by kostyanius** [comment]
i tried to change list(string) to string type for subnet_ids_gitlab_runners and managed to pass for another step, but then also failed with the next error: 
![image](https://user-images.githubusercontent.com/9063908/147925714-4aead1d8-1570-4c01-8c5b-ff10edbe0f85.png)
Thereby i belive the problem is in subnet_ids_gitlab_runners section. Please addvise how to enter in correctly, what formatting?
"subnet-1132132131, subnet-dfdffdfgfg" or subnet-ertt5t5te5,subnet-gfdrt4554tr or "subnet-gdge5e55 subnet-34tt34t3t34"?

**Comment by kayman-mk** [comment]
I think it would be a good idea to place the variables in a file so it becomes easier to test with different setups and running `terraform plan -var-file my-vars.tfvars`

```hcl
aws_region = "eu-west-2"
vpc_id = "vpc-1234"
subnet_id_runners = "subnet-2345"
subnet_ids_gitlab_runner = ["subnet-2345"]
...
```

`subnet_ids_gitlab_runner` is a list of strings and not a string.
