### ISSUE TITLE
http_proxy support missing

### ISSUE THREAD

**Issue by robpearce-flux** [npalm/terraform-aws-gitlab-runner#412]
it'd be good to get support for http_proxy on outbound connections, for pulling the packages, and for the runners connecting back to the git instance.

**Comment by npalm** [comment]
You can inject a custom script in to both agent and docker-machines to set a proy.

**Comment by kayman-mk** [comment]
@robpearce-flux npalm refers to

```hcl
  docker_machine_options           = ["engine-registry-mirror=https://my.docker.proxy"]
```

which is a parameter of the module and sets the docker proxy.

The variables `runners_pre_build_script` and `userdata_pre_install` could also be a good choice to set proxies of any type.

**Comment by kayman-mk** [comment]
@robpearce-flux Can this issue be closed?

**Comment by robpearce-flux** [comment]
yes, thanks.
