### ISSUE TITLE
Add support to disable default tags

### ISSUE THREAD

**Issue by AlbertasG** [npalm/terraform-aws-gitlab-runner#413]
I've hit situation where default module tags `Environment` and `Name` interfere with providers `default_tag` directive. This in result conflict with each Terraform run. 

Introducing something like `default_tags = true` would enable/disable defaults on `local.tags`

Is this a logical feature to add as I'd like to make PR myself.
Maybe there are any workarounds possible? 

 ```
 # module.gitlab-runner.aws_iam_instance_profile.instance will be updated in-place
  ~ resource "aws_iam_instance_profile" "instance" {
        arn         = "arn:aws:iam::1111111111111:instance-profile/staging-instance"
        create_date = "2021-12-03T09:06:50Z"
        id          = "staging-instance"
        name        = "staging-instance"
        path        = "/"
        role        = "staging-instance"
      ~ tags        = {
          + "Environment" = "staging"
            "Name"        = "staging"
        }
        tags_all    = {
            "Environment"    = "staging"
            "Infrastructure" = "v2"
            "ManagedBy"      = "Terraform"
            "Name"           = "staging"
            "Project"        = "Shared"
        }
        unique_id   = "AAAAAAAA"
    }
   ```

**Comment by npalm** [comment]
Thanks for creating, will have a look at the issue in the next day.

**Comment by npalm** [comment]
A PR would be welcome. At the time the module was created, it was also not possible to provide default tags via the provider. Adding an option to disable tagging is welcome! Be-aware there are some tailored tags avaialbe since some orgs requires specific tags on security groups.
