### ISSUE TITLE
Upgrading to 4.36.0 from 4.35.0 gives "runner_registration_token" error on deployment

### ISSUE THREAD

**Issue by sohail-mp** [npalm/terraform-aws-gitlab-runner#418]
Hi

Yesterday we upgraded to 4.36.0 from 4.35.0. 
When deploying the change we received this error:
`Error: Missing map element: This map does not have an element with the key "runner_registration_token".`

My assumption is the error refers to this line number: https://github.com/npalm/terraform-aws-gitlab-runner/blob/e36c97184bc008fdd5ea1a9510cfa520df5b276f/main.tf#L37

We cant figure out how to solve the issue and successfully upgrade to 4.36.0.
We have since reverted our change and gone back to 4.35.0 without any deployment errors. 
Please can someone help?

**Comment by kayman-mk** [comment]
I guess the problem is line 87
`gitlab_runner_registration_token             = var.gitlab_runner_registration_config["registration_token"]`

You have to put the registration_token into the map. Could you please check this?

**Comment by sohail-mp** [comment]
@kayman-mk Yes we have a value set here, just like your example

**Comment by sohail-mp** [comment]
Steps to resolve:
1. remove this resource `module.runner["default"].null_resource.remove_runner` from your remote terraform state
2. plan
3. apply
4. plan again
5. apply again
