### ISSUE TITLE
EC2 created from launch configuration keeps terminating.

### ISSUE THREAD

**Issue by cmbailey87** [npalm/terraform-aws-gitlab-runner#435]
Current using  version = "4.25.0"
and I have my ec2 that is created from the launch group to be a spot instance request. 
https://github.com/npalm/terraform-aws-gitlab-runner/issues/344 

Something that has started recently is the EC2 created from the launch group( the EC2 that deploys the docker machines ) will occasionally, once a week, terminate. 
I have to terminate all the spot requests ( because some show as active and fulfilled ) but there isnt an EC2 running...
OR I have to redeploy the code to the one failing ENV.

I have deployed this same code to multiple ENVs...but only one of the ENVs has this happening. All in the same region.
All ENVs have the same spot requests.

has anyone ran into this issue???
I have my instances set on a schedule and Idle time... could this be the culprit?
if this fixed in a newer version???

thanks in advance.

**Comment by cmbailey87** [comment]
![image](https://user-images.githubusercontent.com/26728086/150378969-27fd809a-14f5-47ea-8df8-14ceef690817.png)
![image](https://user-images.githubusercontent.com/26728086/150382829-4f2bdf4e-d639-483e-a9e8-42cf9356b55c.png)


think i found my issue...i am running into a capacity issues for this account... but only this account.

**Comment by npalm** [comment]
Would suggest to check your AWS limits indeed, please can you update / close the issue when resolved. Thanks for taking the time for sharing!

**Comment by npalm** [comment]
still having this issue?

**Comment by cmbailey87** [comment]
Sorry @npalm , I was out of the office for an extended period...
The issue was resolved, I changed the  EC2 type to a medium , instead of a micro.. The micros seem to be very popular and not alot of the instances were available as spot instances...

Mediums on the other are a plenty.

I will close out the issue. thanks again.
