### ISSUE TITLE
Docker-machine download URL appears to be inaccessible

### ISSUE THREAD

**Issue by JulianCBC** [npalm/terraform-aws-gitlab-runner#457]
It appears that GitLab has made the "generic" `https://gitlab-docker-machine-downloads.s3.amazonaws.com/VERSION/docker-machine` URL inaccessible, so only the "fully qualified" URLs with a system type and architecture work.

```
$ curl https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.12/docker-machine
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>ENYDP0R4QVSFP0QC</RequestId><HostId>iJ7zVyel7aLWz4qEE0lMPpwXbItiAmiud1LkRzwbzts36AqLG1rvINDixGl4Qs2SvrJ1NL7cIYc=</HostId></Error>
```

```
$ curl https://gitlab-docker-machine-downloads.s3.amazonaws.com/v0.16.2-gitlab.12/docker-machine-Linux-x86_64 | file -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 59.8M  100 59.8M    0     0  1957k      0  0:00:31  0:00:31 --:--:-- 2982k
/dev/stdin: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=H8fu0C_uLjkoi-o2ao1v/Greq4F4710ptsLoOLyoB/6Hmp0aU-D8xXDMQeVDPz/wbFjEQ0zwCgSg31oPilA, not stripped
```

I think the simplest solution here would be to just switch the default over to specifying a version instead of a full URL as that appears to do the right thing, and will follow the architecture used on the coordinator EC2 instance without any further configuration.

**Comment by ryancausey** [comment]
Can confirm this issue prevents the runner from starting properly, so I've had to lock to version 4.40.0 for now, as well as manually setting `gitlab_runner_version` to something other than the default of "14.8.0" due to #456.
