### ISSUE TITLE
Supporting Terraform Provider 4

### ISSUE THREAD

**Issue by npalm** [npalm/terraform-aws-gitlab-runner#461]
Thanks to @meMuszr in #444 the initial work is done to provide support for AWS Terraform provider 4. I have merged the PR in #460 to test and fix some minors. All the work is still under test. But would like to gather feedback from the community.

- Feel free to comment on PR #460 and provide suggestions
- Look for people that can run a test on the PR?
- Look for feedback should we already bump the module to Terraform 4.x? You always have the option to use multiple providers if really need. Please comment on the issue.

**Comment by devmohammedothman** [comment]
still not working after upgrade to version 4.4.0, here is the error

```
Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: no available releases match the given constraints ~> 3.35,
│ ~> 4.0

```

**Comment by photosojourn** [comment]
Hey @npalm hope your well. Do you have an eta for this PR being merged? No major rush, but it would allow us to avoid a work around. Thanks for the great work!

**Comment by npalm** [comment]
Since upgrade have major impact, I have crated this issue. To give the community a bit of time to give feedback. If it helps I can tag this branch so you can already start using it.

**Comment by kayman-mk** [comment]
I constantly get a warning in Security Hub that I should use IMDSv2 for EC2 instances. May be it is worth to integrate this as well? Especially as all my executers failed after switching to AWS 4.x provider (see #445)

Security Hub issue: EC2.8 EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)

[IMDSv2 for EC2 in Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#http_tokens)

**Comment by npalm** [comment]
> I constantly get a warning in Security Hub that I should use IMDSv2 for EC2 instances. May be it is worth to integrate this as well? Especially as all my executers failed after switching to AWS 4.x provider (see #445)
> 
> Security Hub issue: EC2.8 EC2 instances should use Instance Metadata Service Version 2 (IMDSv2)
> 
> [IMDSv2 for EC2 in Terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/instance#http_tokens)

Added a solution based on your PR #445 see #490
