### ISSUE TITLE
Having issues with provisioning a EC2 machine

### ISSUE THREAD

**Issue by dhinesh2287** [npalm/terraform-aws-gitlab-runner#473]
I have installed gitlab runner on my instance and register successfully with my gitlab project while building the job iam getting this issue
<img width="960" alt="issue" src="https://user-images.githubusercontent.com/99251741/165513099-779cb165-6658-45ac-9cc8-a84b75a4a7e1.PNG">
This creates an EC2 machine and soon after it destroys it and it keeps retrying.Can any one advise how to solve this issue
Info:
Docker version 20.10.7
docker-machine version 0.16.2-gitlab.12
Below which i given in my config file to create instance

MachineOptions = ["amazonec2-access-key=xxx", "amazonec2-secret-key=xxx", "amazonec2-region=xxx", "amazonec2-vpc-id=xxx", "amazonec2-subnet-id=xxx", "amazonec2-zone=a", "amazonec2-use-private-address=true", "amazonec2-tags=runner-manager-name,gitlab-aws-autoscaler,gitlab,true,gitlab-runner-autoscale,true", "amazonec2-security-group=isnc-sg-gl_runner", "amazonec2-instance-type=t3.micro", "amazonec2-request-spot-instance=true", "amazonec2-spot-price="]
Thanks

**Comment by NK74** [comment]
Same error here

**Comment by NK74** [comment]
Same error here : https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/issues/69#note_925511833
A workaround is available : https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/issues/69 


```
   MachineOptions = [
        "amazonec2-ami=ami-xxxxxxx",
```
(find the AMI for your region here : https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/merge_requests/80/diffs?commit_id=8edea70bb1e6ab34b70fd3b9bf7d59c71eb200ed )

**Comment by dhinesh2287** [comment]
@NK74 issue fixed followed the block which you shared https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/issues/69#note_925511833 
Thanks for the support

**Comment by kayman-mk** [comment]
Might be related to #504

**Comment by kayman-mk** [comment]
@dhinesh2287 According to your last comment, it is fixed. Could you please close it?

**Comment by dhinesh2287** [comment]
yes will close this
