### ISSUE TITLE
Allow setting runners.docker.services in toml

### ISSUE THREAD

**Issue by jonmcewen** [npalm/terraform-aws-gitlab-runner#489]
I've been trying to find a way to configure a docker mirror in the docker+machine runners, but had some problems.  I have set [runners_docker_registry_mirror](https://github.com/npalm/terraform-aws-gitlab-runner#input_runners_docker_registry_mirror)

1. If I set `runners_add_dind_volumes`, then a job script of `docker info` shows the `Registry Mirrors`, but this conflicts with [services](https://docs.gitlab.com/ee/ci/services/) in jobs such as the auto-devops `code_quality` job, which also try to mount `var/run/docker.sock`.
2. If I don't set `runners_add_dind_volumes` (using instead `runners_additional_volumes` to mount all but the docker.sock) then the services start correctly, but `docker info` doesn't show the mirror.

I think I have a workaround though, in which I start a docker service in the runner by [modifying the config.toml](https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#the-service-in-the-gitlab-runner-configuration-file)

I have a requirement that users can use auto-devops without modification, so simply modifying the service(s) in the pipeline config is not an option.

Have I missed a trick, or is adding `[[runners.docker.services]]` a sensible approach?  If so, I'll raise a PR to allow this.

**Comment by jonmcewen** [comment]
See also this issue for more background: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/27173

**Comment by jonmcewen** [comment]
@npalm I'm working on a PR for this. Will be pretty basic initially, but will work for the docker mirror use case

**Comment by kayman-mk** [comment]
If I understand you correctly, @jonmcewen, the problem is, that the mirror disappears if `runners_additional_volumes` is used? Using `runners_add_dind_volumes` everything is fine.

Another question which came into my mind: Why is a job trying to mount a `docker.sock`? Do you have a link to the mentioned `code_quality`job?

**Comment by jonmcewen** [comment]
> If I understand you correctly, @jonmcewen, the problem is, that the mirror disappears if `runners_additional_volumes` is used? Using `runners_add_dind_volumes` everything is fine.
> 
> Another question which came into my mind: Why is a job trying to mount a `docker.sock`? Do you have a link to the mentioned `code_quality`job?

Please see the first comment on this issue: https://gitlab.com/gitlab-org/gitlab-runner/-/issues/4260

Rest assured I spent many days going round in circles on this issue. I stand behind my solution until a better one is proposed.

**Comment by kayman-mk** [comment]
Guess this wasn't closed then #491 was merged months ago.
