### ISSUE TITLE
user-data can log sensitive data

### ISSUE THREAD

**Issue by npalm** [npalm/terraform-aws-gitlab-runner#49]
user-data should not write sensitive information to stdout / logging. Currently the GitLab runner  token is visible

**Comment by kevinrambaud** [comment]
I noticed the registration token is also visible in the tfstate. Do you already have some strategies in mind to hide it?

**Comment by npalm** [comment]
@kevinrambaud yes that is correct, and requires in general a secure way to handle the state. An alternative approach for the runner can be to give an option to provide the key not via the terraform configuration but via a vault or AWS SSM.
