### ISSUE TITLE
instance_type t2.micro does not boot up

### ISSUE THREAD

**Issue by rewb0rn** [npalm/terraform-aws-gitlab-runner#498]
Hi,

I would like to have the gitlab runner use the free-tier t2.micro instance. However when I use `instance_type = "t2.micro"` the EC2 instance is never created and terraform hangs at:

```
module.runner.aws_autoscaling_group.gitlab_runner_instance: Still creating... [8m11s elapsed]
```

Just to check if there is a problem with the parameter itself, I tried both "t3.micro" and "t3.small", and they boot up as expected. I am new to AWS and terraform, so I am not sure how to check any logs. Is there a general problem with "t2.micro" or is there anything I can do to find out why its never being created? The t2.micro instance is not showing up in the EC2 dashboard either.

**Comment by kayman-mk** [comment]
Are you using spot instances? May be there are no machines available? This is the typical problem. You can check it on the EC2 console in AWS.

**Comment by rewb0rn** [comment]
Hey, thanks for your reply. I did check the EC2 dashboard and there are no machines listed. I think if a spot is not available, the machine would be listed there with a note regarding the missing spot? 

I received some emails in the mean time informing me about the problem. I am just guessing but do I need to change the AMI in order to boot up a t2 instead of a t3?

> The launch template cannot be found for an Auto Scaling group in account YYY
>
> Hello,
> 
> At Wed, 25 May 2022 18:43:29 GMT, we detected an issue with your Auto Scaling group XXX in AWS account YYY.
> 
> The launch template associated with this Auto Scaling group cannot be found. Each time a scale out operation is performed, it will be prevented until you make a change that fixes the issue.
> 
> We recommend that you review and update your Auto Scaling group configuration and specify an existing launch template to use.
> 
> Sincerely,
> Amazon Web Services

**Comment by npalm** [comment]
I don't think the AMI is a problem. Normally you can quickly check in the AWS console (EC2) section spot instances for failed spot frequest.

**Comment by rewb0rn** [comment]
I found the solution by attempting to manually launch an instance from the auto scaling group. t2.micro does not support the ebs optimized setting, which is true by default for the runner module. So setting `runner_instance_ebs_optimized = false` inside the runner module was the fix for me. I hope this helps anyone with the same issue.

Should I close this?
