### ISSUE TITLE
No Spot instance request

### ISSUE THREAD

**Issue by jinfanzon** [npalm/terraform-aws-gitlab-runner#508]
Hi I'm facing an issue where no spot instances are being requested, instead I'm getting on-demand instances. My .tf configuration is:

`
module "vpc" {
  source  = "terraform-aws-modules/vpc/aws"
  version = "2.70"

  name = "vpc-${var.environment}"
  cidr = "10.0.0.0/16"

  azs             = [data.aws_availability_zones.available.names[0]]
  private_subnets = ["10.0.1.0/24"]
  public_subnets  = ["10.0.101.0/24"]

  enable_nat_gateway = true
  single_nat_gateway = true
  enable_s3_endpoint = true

  tags = {
    Environment = var.environment
  }
}

module "runner" {
  
  source  = "npalm/gitlab-runner/aws"

  aws_region = var.aws_region
  environment = var.environment
  vpc_id                   = module.vpc.vpc_id
  subnet_ids_gitlab_runner = module.vpc.private_subnets
  subnet_id_runners = element(module.vpc.private_subnets, 0)
  metrics_autoscaling = ["GroupDesiredCapacity", "GroupInServiceCapacity"]

  runners_name = var.runner_name
  runners_gitlab_url = var.gitlab_url
  enable_runner_ssm_access = true
  gitlab_runner_security_group_ids = [data.aws_security_group.default.id]
  runners_request_spot_instance = true
  docker_machine_spot_price_bid = "on-demand-price"
  gitlab_runner_registration_config = {
    registration_token = var.registration_token
    tag_list = "docker_spot_runner,aws"
    description = "AWS runner - Spot"
    locked_to_project = "true"
    run_untagged = "false"
    maximum_timeout = "3600"
  }

  tags = {
    "tf-aws-gitlab-runner:shared" = "runner-default"
    "tf-aws-gitlab-runner:instancelifecycle" = "spot:yes"
  }

  runners_privileged = "true"
  runners_additional_volumes = ["/certs/client"]

  runners_volumes_tmpfs = [
    {
      volume = "/var/opt/cache",
      options = "rw,noexec"
    }
  ]

  runners_services_volumes_tmpfs = [
    {
      volume = "/var/lib/mysql",
      options = "rw,noexec"
    }
  ]

}

resource "null_resource" "cancel_spot_requests" {

  triggers = {
    environment = var.environment
  }

  provisioner "local-exec" {
    when    = destroy
    command = "../../bin/cancel-spot-instances.sh ${self.triggers.environment}"
  }
}`

What should I change in order to get spot instances?

**Comment by kayman-mk** [comment]
Are there any spot requests created (AWS console)?

**Comment by kayman-mk** [comment]
Getting on demand instances = The Agent is an on demand instance or the Executor?

**Comment by jinfanzon** [comment]
Thanks @kayman-mk - There are no spot requests created. And If I go to my ec2 dashboard I do see an ec2 instance created with instance type t3.micro

**Comment by kayman-mk** [comment]
As far as I know you have to set `runner_instance_spot_price` to run the Agent on a spot instance.

**Comment by jinfanzon** [comment]
Thanks! I'll try with that param.
