### ISSUE TITLE
Default AMI for runner in ap-south-1 does not have jq installed

### ISSUE THREAD

**Issue by arrpee** [npalm/terraform-aws-gitlab-runner#51]
### System log:
```
user-data: + chmod +x /tmp/docker-machine
user-data: + cp /tmp/docker-machine /usr/local/bin/docker-machine
user-data: + ln -s /usr/local/bin/docker-machine /usr/bin/docker-machine
user-data: ++ aws ssm get-parameters --names runner-public-runner-token --with-decryption --region ap-south-1
user-data: ++ jq -r '.Parameters | .[0] | .Value'
user-data: /var/lib/cloud/instance/scripts/part-001: line 96: jq: command not found
user-data: + token=
Apr 03 06:55:56 cloud-init[2236]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [127]
```

**Comment by arrpee** [comment]
Probably should add **yum install jq -y** to gitlab-runner.tpl ?

**Comment by npalm** [comment]
Sound as a good plan, feel free to create a PR.

**Comment by npalm** [comment]
@arrpee I just tested the runner in ap-south-1, seems like working, jq is installed. Which AMI do you used, the one selected by terraform module? I have got ami `amzn-ami-hvm-2018.03.0.20181129-x86_64-ebs (ami-00a5aa934dc5052b4)` which has jq.

**Comment by arrpee** [comment]
So after a fresh clone, I can't seem to replicate it anymore. The module does select `amzn-ami-hvm-2018.03.0.20181129-x86_64-ebs` which functions properly. I'll investigate a bit and get back to you

**Comment by arrpee** [comment]
Okay I just can't seem to replicate it anymore so I'm closing the issue.
