### ISSUE TITLE
Job trace streaming

### ISSUE THREAD

**Issue by batistadasilva** [npalm/terraform-aws-gitlab-runner#518]
Hello everybody

Are you also having no job traces on GitLab web interface while the job is running? I can see no logs during the job execution, then they all appear at once when the job is finished.

Thank you

**Comment by kayman-mk** [comment]
Not really. Sometimes there is a little lag, but in general the job output is shown immediately.

**Comment by batistadasilva** [comment]
Thank you for the response!

Would anyone have any clue of what am I missing? Maybe some bad network setup?

**Comment by kayman-mk** [comment]
Did you check, that the GitLab Runner version matches your Gitlab version? And in case you are using a Runner helper image: it should match the Runner version.

**Comment by batistadasilva** [comment]
My mistake, there was juste some little lags indeed
