### ISSUE TITLE
Duplicate tag key 'Name' error with newer docker-machine version

### ISSUE THREAD

**Issue by long-wan-ep** [npalm/terraform-aws-gitlab-runner#521]
When setting `docker_machine_version` to >=0.16.2-gitlab.16, I'm seeing the following error when the runner tries to create docker-machine ec2 instances:
```
{
    "driver": "amazonec2",
    "level": "error",
    "msg": "Error creating machine: Error in driver during machine creation: Error launching instance: InvalidParameterValue: Duplicate tag key 'Name' specified.",
    "name": "runner-zeq53ex4-runner-1658964971-a77712f5",
    "operation": "create",
    "time": "2022-07-27T23:36:15Z"
}
```

This looks to be cause by [this change](https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/merge_requests/68) in gitlab's docker-machine, which is present in version 0.16.2-gitlab.16 and above. Both the [runner config](https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/main.tf#L92) and [docker-machine](https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/blob/v0.16.2-gitlab.18/drivers/amazonec2/amazonec2.go#L1106) adds a `Name` tag for the instance, which will cause a conflict in the newer docker-machine versions since tags are now being added at instance creation time instead of after instance creation.

I think removing the `Name` tag from https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/main.tf#L92 and letting docker-machine create the `Name` tag from the MachineName could be a solution.

**Comment by jccl** [comment]
The ability to use Amazon Linux 2 for runners is now available in docker-machine v0.16.2-gitlab.18 (https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/issues/66#note_1030083237). Having this fixed would really benefit people that would like to use Amazon's OS.

**Comment by ntman4real** [comment]
any work around other than reverting back to previous module version?

**Comment by kayman-mk** [comment]
The variables `docker_machine_download_url` and `docker_machine_version` could be helpful to switch the docker+machine only.

**Comment by long-wan-ep** [comment]
@kayman-mk Thanks for picking this up, hope this will get released soon. Being able to use Amazon Linux 2 would be a great improvement for us.

**Comment by kayman-mk** [comment]
@long-wan-ep @jccl  @ntman4real Any chance to get this checked by you? Did several tests in my environment and didn't found any problem. 

#522

**Comment by long-wan-ep** [comment]
This worked for me using docker-machine 0.16.2-gitlab.18 and a centos AMI. I did run into an issue with Amazon Linux 2 AMIs where it errored trying to install docker, but it looks to be an issue with GitLab's docker-machine implementation.

The only issue I found was the `name_docker_machine_runners` override is not working now that the `Name` tag isn't being added.

**Comment by kayman-mk** [comment]
Yeah, as there is no Name tag anymore it can't be overwritten. This functionality is dropped with the 0.16.2 of the docker-machine. That's true.
I added the following to the variable description: `(ignored for `docker_machine_version` >= 0.16.2)`

**Comment by long-wan-ep** [comment]
docker-machine creates the `Name` tag from the machine name, is it possible to updated https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/template/runner-config.tpl#L48 to use `name_docker_machine_runners` if it's set?

**Comment by kayman-mk** [comment]
Yeah, but seems to be tricky. I have no idea what strings can be used, e.g. setting the `MachineName` to `runner` ends up with

```
"driver":"amazonec2","level":"error","msg":"Error creating machine: Invalid hostname specified. Allowed hostname chars are: 0-9a-zA-Z . -","name":"runner-ewr83ykp-runner%!(EXTRA string=1660377276-3bf3eb5d)","operation":"create","time":"2022-08-13T07:54:36Z"}
{"error":"exit status 1","fields.time":30579290,"level":"error","msg":"Machine creation failed","name":"runner-ewr83ykp-runner%!(EXTRA string=1660377276-3bf3eb5d)","time":"2022-08-13T07:54:36Z"}
```

**Comment by kayman-mk** [comment]
Ok, got it. The `MachineName` has to include `%s` which makes the name unique. So there is no way to overwrite something.

The only option I see is, that we could use the old `Name` (and `overwrite`) as a prefix.

**Comment by kayman-mk** [comment]
@long-wan-ep Please have a look at #522. May be you could check the new name of the machines? I added the `var.overrides["name_docker_machine_runners"]` as a prefix.
