### ISSUE TITLE
Refactor cache module

### ISSUE THREAD

**Issue by kayman-mk** [npalm/terraform-aws-gitlab-runner#525]
As far as I can see, all resources in the cache module have a count attribute which is set to 1 if the `create_cache_bucket` equals true.

But why should I set the flag to `false` and call the module? It would do nothing at all and I could simply omit the whole call.

The benefit would be a simpler module:
- no `count` attributes and thus simple resources instead of lists
- outputs could return the plain value instead of reading lists
- easier to understand and maintain

The only caller I know is the runner module. But I think there are only small changes to do if any.

I'd like to refactor this module in a PR. Any thoughts and things to consider?

**Comment by dsalaza4** [comment]
I think this relates to #298

**Comment by long-wan-ep** [comment]
Hi, I'm seeing the following errors on version 5.2.0 and I think it's related to this change:

```
│ Error: Unsupported attribute
│
│   on .terraform/modules/runner_upgrade_test.runner/main.tf line 296, in locals:
│  296:   bucket_name   = var.cache_bucket["create"] ? module.cache.bucket : lookup(var.cache_bucket, "bucket", "")
│     ├────────────────
│     │ module.cache is tuple with 1 element
│
│ This value does not have any attributes.
╵
╷
│ Error: Unsupported attribute
│
│   on .terraform/modules/runner_upgrade_test.runner/main.tf line 297, in locals:
│  297:   bucket_policy = var.cache_bucket["create"] ? module.cache.policy_arn : lookup(var.cache_bucket, "policy", "")
│     ├────────────────
│     │ module.cache is tuple with 1 element
│
│ This value does not have any attributes.
```

Wouldn't `module.cache` need to be accessed through index now that it uses `count`?

**Comment by kayman-mk** [comment]
I think so too. Strange that I didn't get an error. Preparing a fix.
