### ISSUE TITLE
Error creating instance - Hostname too long

### ISSUE THREAD

**Issue by jonpas** [npalm/terraform-aws-gitlab-runner#536]
v5.2.0+ creates runner instances with very long names, eg. `runner-2stajshg-gitlab-runner-beefy-docker-machine-1661510762-2a25d6d4` (where `gitlab-runner-beefy` is our environment name). This causes the instances to fail to create with the following errors in CloudWatch:

```
Aug 26 10:46:31 ip-10-63-101-56 gitlab-runner: {
    "driver": "amazonec2",
    "level": "error",
    "msg": "Error creating machine: Error running provisioning: ssh command error:",
    "name": "runner-2stajshg-gitlab-runner-beefy-docker-machine-1661510762-2a25d6d4",
    "operation": "create",
    "time": "2022-08-26T10:46:31Z"
}

Aug 26 10:46:31 ip-10-63-101-56 gitlab-runner: {
    "driver": "amazonec2",
    "level": "error",
    "msg": "command : sudo hostname runner-2stajshg-gitlab-runner-beefy-docker-machine-1661510762-2a25d6d4 && echo \"runner-2stajshg-gitlab-runner-beefy-docker-machine-1661510762-2a25d6d4\" | sudo tee /etc/hostname",
    "name": "runner-2stajshg-gitlab-runner-beefy-docker-machine-1661510762-2a25d6d4",
    "operation": "create",
    "time": "2022-08-26T10:46:31Z"
}

Aug 26 10:46:31 ip-10-63-101-56 gitlab-runner: {
    "driver": "amazonec2",
    "level": "error",
    "msg": "err     : exit status 1",
    "name": "runner-2stajshg-gitlab-runner-beefy-docker-machine-1661510762-2a25d6d4",
    "operation": "create",
    "time": "2022-08-26T10:46:31Z"
}

Aug 26 10:46:31 ip-10-63-101-56 gitlab-runner: {
    "driver": "amazonec2",
    "level": "error",
    "msg": "output  : hostname: name too long",
    "name": "runner-2stajshg-gitlab-runner-beefy-docker-machine-1661510762-2a25d6d4",
    "operation": "create",
    "time": "2022-08-26T10:46:31Z"
}
```

**Comment by kayman-mk** [comment]
Same problem here. Tried the update today and it failed.

**Comment by macnibblet** [comment]
Same here, have managed to figure out how to solve it? I tried downgrading but an older version but that didn't help.

**Comment by kayman-mk** [comment]
No solution so far. Downgrading to 5.1.0 worked here. Using shorter hostnames is also not working. The machine is created and dies seconds later.

**Comment by kayman-mk** [comment]
Hmm, strange. Shortening the hostname works.

```
  overrides = {
    name_sg                     = ""
    name_iam_objects            = ""
    name_runner_agent_instance  = "Gitlab-Agent-TEST-${local.gitlab_test_subnet.availability_zone}"
    name_docker_machine_runners = "TEST"
  }
```

Set a short value for `name_docker_machine_runners` does the job.

**Comment by kayman-mk** [comment]
Did some analysis on one of my runners:
- maximum hostname length is 64 characters
- the default name set by the docker machine driver is 35 characters long

Thus the maximum user defined part of the hostname is 64-35-1=28 characters (`-1` as we loose one character for a hyphen to separate our name from the one added by the docker machine driver).

Example:
```
  overrides = {
    name_sg                     = ""
    name_iam_objects            = ""
    name_runner_agent_instance  = "Gitlab-Agent-TEST-${local.gitlab_test_subnet.availability_zone}"
    name_docker_machine_runners = "TEST"
  }
```

The runners are named like `runner-TEST-2345014313-f7a3debe`

**Comment by nathan-gilbert** [comment]
Bumping into this problem today. Anyone know when the fix will be released?

**Comment by toxinu** [comment]
Same problem here.

**Comment by bishtawi** [comment]
I am running into this bug too. For now I've downgraded to `5.1.0` which fixed the problem.
