### ISSUE TITLE
Is the cache cleanup lifecycle working?

### ISSUE THREAD

**Issue by kayman-mk** [npalm/terraform-aws-gitlab-runner#539]
I think there are some issues with cleaning up the S3 cache.

# S3 Lifecycle Prefix
After installing a fresh Gitlab Runner and S3 cache I noticed that the prefix within the S3 cache is `project` and not `runner`. But this is the default setting when a new cache is created. This was also mentioned in #200 
This could be 
- a configuration issue of the user (but I didn't found any special configuration on my side)
- a change within the Gitlab Runner project (renamed cache directory) which we didn't notice

https://github.com/npalm/terraform-aws-gitlab-runner/blob/5b6e342467557ca3e5c6567ee01fb3b0d2ccc5de/modules/cache/variables.tf#L59-L63

# S3 Lifecycle
The lifecycle rule touches files within the bucket not its content. This means that objects which are not updated (no longer in use, e.g. caches from deleted Gitlab projects) are deleted. But I think this does not happen very often as the majority of all projects in Gitlab is never deleted or archived.

What I see in my cache is that it constantly grows as old objects within the cache zip file are never deleted. This results in higher storage costs and slower pipelines as the amount of data grows over the time.

# Suggestion
1. Change the default setting of the lifecycle prefix as mentioned above to activate the clean up.
2. Clean the cache files, e.g. unzip the cache, delete old files, zip and upload the cache again.

What do you think?

**Comment by brennerm** [comment]
Seeing the same behavior. All cache files are being created under the `project/` prefix but the lifecycle rule only applies to files with the `runner/` prefix.

Bucket content:
![image](https://user-images.githubusercontent.com/5527832/208416216-bdcb6665-fcc0-488b-b9d1-9204ac2f773c.png)


Lifecycle config:
![image](https://user-images.githubusercontent.com/5527832/208416179-ae613055-7d39-49f5-9007-e3ec0ba652c6.png)

**Comment by tmeijn** [comment]
@kayman-mk I think the answer lies here: https://gitlab.com/gitlab-org/gitlab-runner/-/blob/0ae4ec1d8b68ec9cb410466674fec799fef30707/cache/cache.go#L25-33

```go
	// runners get their own namespace, unless they're shared, in which case the
	// namespace is empty.
	namespace := ""
	if !config.GetShared() {
		namespace = path.Join("runner", build.Runner.ShortDescription())
	}

	basePath := path.Join(config.GetPath(), namespace, "project", strconv.FormatInt(build.JobInfo.ProjectID, 10))
	fullPath := path.Join(basePath, key)

```

This code says to me that if the cache is NOT shared, then path `runner/[RUNNER_ID]/project/[PROJECT_ID]/etc...`

And if it is shared, then path `project/[PROJECT_ID]/etc...`, basically omiting the runner id namespacing, which makes sense.

**Comment by tmeijn** [comment]
Did some validation:

config:

```hcl
  cache_shared = "true"
  }
```
Results in a cache path prefixed by `project`:

![image](https://user-images.githubusercontent.com/17970041/221147027-fa58915b-b867-4b8d-94ba-14cf4b8b278c.png)

```hcl
  cache_shared = "false"
  }
```

Results in a cache path prefixed by `runner/[RUNNER_ID]`:

![image](https://user-images.githubusercontent.com/17970041/221149154-3ecd4fcd-7044-47b7-8b34-dfaeead5b67c.png)

Should be an easy enough fix, I'll put up a PR!
