### ISSUE TITLE
Public key of gitlab runner repo is not verified

### ISSUE THREAD

**Issue by baolsen** [npalm/terraform-aws-gitlab-runner#562]
Example warning in cloudwatch

2022-10-31T15:20:41.254+02:00 | warning: /var/cache/yum/x86_64/2/runner_gitlab-runner/packages/gitlab-runner-15.3.0-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 35dfa027: NOKEY

  | 2022-10-31T15:20:41.255+02:00 | Public key for gitlab-runner-15.3.0-1.x86_64.rpm is not installed

**Comment by kayman-mk** [comment]
Could you please give some more details on what happened where?

**Comment by baolsen** [comment]
Thanks for the feedback. 
So I'm not sure if this is a significant issue or not, but I found this warning in cloudwatch.

It appears a shirt while after this script has completed running:
https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh

I can see the output of that script in the logs:
Nov  4 08:56:44 ip-10-235-150-169 user-data: The repository is setup! You can now install packages.

Then this command starts:
Nov  4 08:56:44 ip-10-235-150-169 user-data: + yum install gitlab-runner-15.3.0 -y
While that yum install is executed, I see the warning.
```
...
Nov  4 08:56:46 ip-10-235-150-169 user-data: Downloading packages:
Nov  4 08:57:02 ip-10-235-150-169 user-data: warning: /var/cache/yum/x86_64/2/runner_gitlab-runner/packages/gitlab-runner-15.3.0-1.x86_64.rpm: Header V4 RSA/SHA512 Signature, key ID 35dfa027: NOKEY
Nov  4 08:57:02 ip-10-235-150-169 user-data: Public key for gitlab-runner-15.3.0-1.x86_64.rpm is not installed
```
A few lines later:
```
Nov  4 08:57:03 ip-10-235-150-169 user-data: Retrieving key from https://packages.gitlab.com/runner/gitlab-runner/gpgkey
Nov  4 08:57:03 ip-10-235-150-169 user-data: Retrieving key from https://packages.gitlab.com/runner/gitlab-runner/gpgkey/runner-gitlab-runner-4C80FB51394521E9.pub.gpg
Nov  4 08:57:04 ip-10-235-150-169 user-data: Importing GPG key 0x35DFA027:

```

Perhaps the warning from yum is harmless, if the GPG key is verified a little later on. Not sure.

**Comment by kayman-mk** [comment]
As the key is installed automatically it will hopefully used to verify the downloaded package. If so we can ignore the warning as everything is fine.

**Comment by baolsen** [comment]
Agree, this is probably not a concern just a misleading log entry. Closing.
