### ISSUE TITLE
Suggestion: Tag EC2 instance with runner tag_list tags

### ISSUE THREAD

**Issue by baolsen** [npalm/terraform-aws-gitlab-runner#568]
To make runners simpler to identify and understand, an EC2 instance tag/tags could be added which match the gitlab runner tag list.

**Comment by npalm** [comment]
Not sure if I understand the problem, what are you missing? Runners are tagged with the parent (agent creates the instane). and a tag to indicate the runner.

**Comment by kayman-mk** [comment]
The runners show these tags at the moment (snapshot from my environment)
 - gitlab-runner-parent-id, e.g. i-0fed3a3ec404exxxx
- Name, e.g. runner-kszeurwd-Uncritical-eu-central-1b-1679128951-fafa7701
- Environment, e.g. prod-gitlab-ci-runner-uncritical-b

**Comment by baolsen** [comment]
Thanks for the feedback.

To clarify, I thought it would be useful to have the EC2 instance tagged with the value of `gitlab_runner_registration_config.tag_list`

But I'll close this issue, there is a `tags` variable which can be used for arbitrary additional tags so I can use that.
