### ISSUE TITLE
Allow adding part to user_data

### ISSUE THREAD

**Issue by rgarrigue** [npalm/terraform-aws-gitlab-runner#570]
Hello

I'ld like to have a new var where I could add some more script to be run at the end of the module's own user_data. 

Typically I want to add a `company` user with a `ops.pub` public key in authorized_keys. We use that with all of our instances, so any ops with the private key + access to SSM + a small SSH config can just `ssh i-01234567889` for some troubleshooting. 
Currently if I need to troubleshoot something, I've no better choice than using the AWS EC2 Console to connect via the Session Manager tab. Okay-ish but could be way more convenient.

Thanks for the module :)

**Comment by kayman-mk** [comment]
I prefer to SSM connection. No open ports --> no vulnerabilities.

You can also tunnel the SSH traffic through the SSM from the local machine. Please have a look at https://github.com/Hapag-Lloyd/terraform-aws-bastion-host-ssm/blob/main/scripts/connect_bastion.sh

**Comment by rgarrigue** [comment]
I know, that's what I'm doing.

But we still want a shared SSH key for the ops team there. And installing our monitoring agent. Etc.

**Comment by kayman-mk** [comment]
Why not use the `userdata_post_install` variable?
