### ISSUE TITLE
Question: Escape runners_pre_build_script to include env-variable

### ISSUE THREAD

**Issue by deveth0** [npalm/terraform-aws-gitlab-runner#576]
Hi there,

i'm struggling with the `runners_pre_build_script` variable I need to set as we otherwise run into rate limits for `dind` builds.

The correct value (verified by setting it manually) is:
`pre_build_script="mkdir -p $HOME/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json"`

And here comes the pain and I'm running out of ideas, how I can configure this value and get it into my instance correctly.

I tried all of the following versions (some are invalid, some result in `\$HOME`, the first one is simply set without the env-variables as those are substitued during the build) but none has worked so far.
```
runners_pre_build_script = "\"mkdir -p $HOME/.docker && echo $DOCKER_AUTH_CONFIG > $HOME/.docker/config.json\""
runners_pre_build_script = "\"mkdir -p \$HOME/.docker && echo \$DOCKER_AUTH_CONFIG > \$HOME/.docker/config.json\""
runners_pre_build_script = "\"mkdir -p $$HOME/.docker && echo $$DOCKER_AUTH_CONFIG > $$HOME/.docker/config.json\""
runners_pre_build_script = "\"mkdir -p \\$$HOME/.docker && echo \\$$DOCKER_AUTH_CONFIG > \\$$HOME/.docker/config.json\""
runners_pre_build_script = "\"mkdir -p \\$HOME/.docker && echo \\$DOCKER_AUTH_CONFIG > \\$HOME/.docker/config.json\""
```

I'd really appreciate any help here as I'm running out of ideas :-/

Thanks in advance

**Comment by kayman-mk** [comment]
Oh yes, it's a pain. There are some pitfalls and it is more or less try and error.

I checked my configuration. In Terraform I defined
```hcl
module "gitlab_runner" {
  runners_pre_build_script = file("${path.module}/templates/runners_pre_build_script")
}
```

And runners_pre_build_script looks like
```
"""
  eval \$(ssh-agent)

  mkdir -p ~/.ssh
  echo "\$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
  chmod 0644 ~/.ssh/known_hosts
"""
```

**Comment by deveth0** [comment]
hi, I was not able to test that yet, but the solution sounds feasible, thank you so much!
