### ISSUE TITLE
name of the instance in the ASG should be different than just "var.environment"

### ISSUE THREAD

**Issue by allanlegalstart** [npalm/terraform-aws-gitlab-runner#58]
currently we have no way to put a name different than the environment, and it's a bit confusing to have a instance named "dev" 
that's especially true if one wants to have several ASG , like one with GPU instances , tagged with "has-gpu" (to run some specific task)  and one named "low-cpu-instances"   , both in the same environment

**Comment by npalm** [comment]
@allanlegalstart I agree, feel free to make a PR. It would be great if you can make the change in such way that it remains backwards compatible. I expect also a few changes on the name of the instance, and security groups. Just to override the defaults. Maybe that can inspire you as well. I hope those changes will be back in a week or so.

**Comment by allanlegalstart** [comment]
@npalm  I can give it a shot,  something in the line of "if new_variable_for_name not defined then fallback to var.environment" ?

**Comment by npalm** [comment]
@allanlegalstart sorry for the late response. We have added a map to override default values (see variables.tf file). Does it fit for you to add your overrides to this map? Otherwise feel free to give it a shot :)

**Comment by allanlegalstart** [comment]
I will try it and tell you, but so far looks good

**Comment by allanlegalstart** [comment]
hmmm simply adding 

```terraform
module runner {
  source  = "github.com/npalm/terraform-aws-gitlab-runner?ref=cfe4c83c9034"
  name_runners_docker_machine = "service-gitlab-runner-docker-machine"
}
```

didn't work, we needed to do this :
```
module runner {
  source  = "github.com/npalm/terraform-aws-gitlab-runner?ref=cfe4c83c9034"
  overrides = {
    name_sg                     = "service-gitlab-runner-sg"
    name_runner_agent_instance  = "service-gitlab-runner-agent"
    name_docker_machine_runners = "service-gitlab-runner-docker-machine"
  }
}

```

not sure if expected or not

**Comment by npalm** [comment]
@allanlegalstart yep you have to explicit define those overrides via the map.  Since those override are really for specific situations. Could this work for you? Feel free to create a proposal for the option you need.

**Comment by allanlegalstart** [comment]
wait sorry I didn't see that actually I was not using `name_runners_docker_machine`  in the overrides but something else.
now that i see that, my question is more : why using `name_runners_docker_machine`  didn't work ?

**Comment by npalm** [comment]
Ok, I have to check it.

**Comment by npalm** [comment]
@allanlegalstart `name_runners_docker_machine` was not working since its look like a left over. At this time the variable is completely removed. Shall we close the issue?

**Comment by allan-simon** [comment]
yes I think we can :)
