### ISSUE TITLE
📢 Welcome new maintainer  Matthias Kay  🙌

### ISSUE THREAD

**Issue by npalm** [npalm/terraform-aws-gitlab-runner#593]
I am super happy to welcome @kayman-mk as maintainer to the project. A quick count learned Matthias got 44 PRs merged since July 2020. Which is even more than the release bot! 

Onboarding

- [x] Invite
- [ ] Assign maintainer role
- [x] Add CODEOWNER file
- [x] Update branch protection rules

**Comment by kayman-mk** [comment]
Thanks for the warm welcome, Niek. The next 44 PRs are on my list. :-)

**Comment by npalm** [comment]
Since the repository is not part of an org but user space no specific role can be assigned besides collaborator.
