### ISSUE TITLE
Cache SSE permissions are missing

### ISSUE THREAD

**Issue by jonmcewen** [npalm/terraform-aws-gitlab-runner#610]
Since the change to using the module managed KMS key for cache bucket SSE, the runner doesn't have the required permissions to create/read the cache.

Solution could be to add another policy document to the -docker-machine-cache policy, something like:

```
data "aws_iam_policy_document" "runner_kms" {
  statement {
    actions = [
      "kms:Decrypt",
      "kms:GenerateDataKey"
    ]

    resources = [
      data.aws_kms_key.runner_kms.arn
    ]
  }
}
```

**Comment by kayman-mk** [comment]
I remember that I deployed the module into my accunt to make sure that the new infrastructure is working.

May be I have a "*" permission somewherevin my roles. Have to check that.

**Comment by kayman-mk** [comment]
Checked the variable descriptions. I think the caller has to make sure that the key is accessible. 

We have a similar variable in the root module to encrypt the Cloudwatch logs `kms_key_id`. And the description says: Ensure proper access.

So I propose to amend the variable description in the cache module and close the issue.

@jonmcewen @npalm What do you think?
