### ISSUE TITLE
Broken Examples link

### ISSUE THREAD

**Issue by demisx** [npalm/terraform-aws-gitlab-runner#63]
The example link throughout documentation returns 404. https://registry.terraform.io/modules/npalm/gitlab-runner/aws/3.2.0

**Comment by npalm** [comment]
@demisx thanks for creating an issue. But for me it is not clear to which link you refer. Is a link on the terraform registry not working? Or a link in the README?

**Comment by demisx** [comment]
NP. The example links on https://registry.terraform.io/modules/npalm/gitlab-runner/aws/3.2.0 seem to be broken. I am attaching a couple of screenshots to illustrate:

![Screen Shot 2019-05-14 at 11 41 30 AM](https://user-images.githubusercontent.com/4452412/57723446-79cbe900-763d-11e9-94c2-3a01f6473480.gif)

![Screen Shot 2019-05-14 at 11 40 05 AM](https://user-images.githubusercontent.com/4452412/57723450-7d5f7000-763d-11e9-8e80-22a5f87fc010.gif)

**Comment by npalm** [comment]
@demisx thanks

**Comment by npalm** [comment]
@demisx the links are relative links in github and therefore not working in the Terraform registry. WIll fix them in the next release.

**Comment by npalm** [comment]
https://github.com/hashicorp/terraform/issues/21452

**Comment by kevinrambaud** [comment]
What about using absolute links in the meantime this is fixed? I can open a PR if needed.

**Comment by npalm** [comment]
Is an option. But then for each release the links needs to be updated. So another ideaa could be en sed or awk expression. That updates the readme. What do you think?

**Comment by npalm** [comment]
@kevinrambaud @demisx  I have create a small fix. See here a sample of the readme for this branch. By default it links to develop unless the env var `GIT_REF` is set before running autodocs

https://github.com/npalm/terraform-aws-gitlab-runner/blob/fix/63-broken-example-links/README.md

**Comment by kevinrambaud** [comment]
Well done, sounds good.
