### ISSUE TITLE
can't enable ssh access to the runner instance

### ISSUE THREAD

**Issue by philippefuentes** [npalm/terraform-aws-gitlab-runner#64]
Hi @npalm and thank you for this great module, just starting with gitlab CI.

I wanted to enable ssh in the runner instance by using the variable:

```
enable_gitlab_runner_ssh_access=true
```
after running the plan the first time with the default value at "false"

It does create a new sg with port 22 (aws_security_group.runner-ssh) but the launch configuration still refers to the first created sg (aws_security_group.runner)

what am I missing ?
Thank you

**Comment by npalm** [comment]
@philippefuentes thanks for reporting the issue, will check it this week

**Comment by philippefuentes** [comment]
@npalm I also noticed that the `runner_ssh` security group does not have any `egress` attached.

So in the end what I did is getting rid of the additional `runner_ssh` sg and simply attached the `runner_ssh` sg rule to the existing `runner` sg  (it's already got an `egress` configured) according to the value of `enable_gitlab_runner_ssh_access`:

```
resource "aws_security_group_rule" "runner_ssh" {
  count = "${var.enable_gitlab_runner_ssh_access ? 1 : 0}"

  type        = "ingress"
  from_port   = 22
  to_port     = 22
  protocol    = "tcp"
  cidr_blocks = ["${var.gitlab_runner_ssh_cidr_blocks}"]

  security_group_id = "${aws_security_group.runner.id}"
}
```

So basically, you'll notice that in the updated code above, `security_group_id` refers to the `runner` sg instead of the former `runner_ssh` sg that I deleted.

**Comment by npalm** [comment]
Yep thanks, the security group `runner_ssh` is not used at all. Busy with a fix
