### ISSUE TITLE
`docker+machine` Executor Is Not Working In `eu-central-2` AWS Region

### ISSUE THREAD

**Issue by halaoner** [npalm/terraform-aws-gitlab-runner#660]
# Describe the bug

GitLab CI pipeline fails when the solution is deployed in `eu-central-2` AWS region because `docker+machine` executor is [not supported](https://docs.docker.com.xy2401.com/machine/drivers/aws/) in `eu-central-2` region.

# To Reproduce

1. Having the terraform module:`npalm/gitlab-runner/aws` - version = `5.9.0` 

2. AWS region: `eu-central-2`

3. Provision infrastructure by running: `terraform plan && terraform apply`

4. Infrastructure in AWS is successfully provisioned.

5. Gitlab Runner Manager is registered with the GitLab repository:

<img width="840" alt="image" src="https://user-images.githubusercontent.com/63114209/212655431-2eeff82b-82ce-4540-a3be-0587f94eca26.png">

6. Trigger CI pipeline in the GitLab repo.

7. Pipeline fails:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/63114209/212655507-f986b9cd-8121-4274-96ff-1614ba37324f.png">

# Expected behavior

- Scaling out works - Gitlab Runner Manager provisions new EC2 spot instances that run a CI job.
- GitLab CI pipeline pass.
- Scaling in works.

# Additional context

## AWS Environment - Logs From CloudWatch

```json
Jan 13 13:04:57 ip-10-0-1-235 gitlab-runner: 
{
    "driver": "amazonec2",
    "level": "error",
    "msg": "Error setting machine configuration from flags provided: Invalid region specified",
    "name": "runner-6kjscxd-runners-dev-1673615097-6f5cf581",
    "operation": "create",
    "time": "2023-01-13T13:04:57Z"
}

Jan 13 13:04:57 ip-10-0-1-235 gitlab-runner: 
{
    "error": "read |0: file already closed",
    "level": "warning",
    "msg": "Problem while reading command output",
    "time": "2023-01-13T13:04:57Z"
}

Jan 13 13:04:57 ip-10-0-1-235 gitlab-runner: 
{
    "error": "exit status 1",
    "fields.time": 43137570,
    "level": "error",
    "msg": "Machine creation failed",
    "name": "runner-6kjscxd-runners-dev-1673615097-6f5cf581",
    "time": "2023-01-13T13:04:57Z"
}

Jan 13 13:05:01 ip-10-0-1-235 gitlab-runner: 
{
    "duration_s": 18.42350433,
    "job": 2455638,
    "level": "error",
    "msg": "Job failed (system failure): exit status 1",
    "project": 4140,
    "runner": "6kjs_cxd",
    "time": "2023-01-13T13:05:01Z"
}

Jan 13 13:05:01 ip-10-0-1-235 gitlab-runner: 
{
    "builds": 0,
    "error": "exit status 1",
    "executor": "docker+machine",
    "level": "warning",
    "msg": "Failed to process runner",
    "runner": "6kjs_cxd",
    "time": "2023-01-13T13:05:01Z"
}

```

## Local Test

`.aws/config` setup with `eu-central-2` region

```bash
$ docker-machine create --driver amazonec2 --amazonec2-region eu-central-2 aws01
Error setting machine configuration from flags provided: Invalid region specified
```

## `docker` executor

Autoscaling is not supported when the `docker` executor is used (if I am not mistaken - see [A Brief Guide to GitLab CI Runners and Executors](https://medium.com/devops-with-valentine/a-brief-guide-to-gitlab-ci-runners-and-executors-a81b9b8bf24e)).

- GitLab CI pipeline runs but scaling out is not working when changing the executor for `docker`

<img width="1142" alt="image" src="https://user-images.githubusercontent.com/63114209/212660578-ff4ace35-c091-4b6e-86a0-d3ab7b40eea7.png">

- Terraform snippet (`variables.tf`)

```terraform
variable "runners_executor" {
  description = "The executor to use. Currently supports `docker+machine` or `docker`."
  type        = string
  default     = "docker"
}
```

Error:

```bash
{"builds":0,"error":"exit code 1","executor":"docker","level":"warning","msg":"Failed to process runner","runner":"6kjs_cxd","time":"2023-01-13T12:32:12Z"}
```

**Comment by kayman-mk** [comment]
Sounds interesting. Have to investigate this and will try to install the runner in eu-central-2 too.

**Comment by kayman-mk** [comment]
Problem found. The regions are checked in the docker-machine driver. I created a merge request in the project. We have to wait for it and upgrade to the new version.

[GitLab/docker-machine merge request](https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/merge_requests/99)

**Comment by kayman-mk** [comment]
GitLab docker-machine reviewers not available in January.

**Comment by halaoner** [comment]
Hi @kayman-mk, do you have already a plan when the `eu-central-2` and other regions will be available for `docker+machine` executor ([GitLab merge request](https://gitlab.com/gitlab-org/ci-cd/docker-machine/-/merge_requests/99) was already reviewed and merged)?

**Comment by kayman-mk** [comment]
Due to all the problems within the docker+machine and the Docker v23 update: It could be the case that it is already working with version 5.9.1 of this module. Do you have the chance to test it?

**Comment by halaoner** [comment]
Yes, I will try it to provision resources into `eu-central-2` region.

**Comment by halaoner** [comment]
I am getting still the same error into deploying the solution in to `eu-central-2` region:

### GitLab CI/CD pipeline:

![image](https://user-images.githubusercontent.com/63114209/219002540-4c2076fe-9582-4bc2-9d83-82bdadafa81b.png)


### AWS Cloudwatch Logs:

```json
Feb 15 10:13:16 ip-10-0-1-23 gitlab-runner: 
{
    "driver": "amazonec2",
    "level": "error",
    "msg": "Error setting machine configuration from flags provided: Invalid region specified",
    "name": "runner-yyehpyy-runners-dev-1676455996-da045408",
    "operation": "create",
    "time": "2023-02-15T10:13:16Z"
}

Feb 15 10:13:16 ip-10-0-1-23 gitlab-runner: 
{
    "error": "read |0: file already closed",
    "level": "warning",
    "msg": "Problem while reading command output",
    "time": "2023-02-15T10:13:16Z"
}

Feb 15 10:13:16 ip-10-0-1-23 gitlab-runner: 
{
    "error": "read |0: file already closed",
    "level": "warning",
    "msg": "Problem while reading command output",
    "time": "2023-02-15T10:13:16Z"
}

Feb 15 10:13:16 ip-10-0-1-23 gitlab-runner: {
    "error": "exit status 1",
    "fields.time": 41118903,
    "level": "error",
    "msg": "Machine creation failed",
    "name": "runner-yyehpyy-runners-dev-1676455996-da045408",
    "time": "2023-02-15T10:13:16Z"
}

Feb 15 10:13:16 ip-10-0-1-23 gitlab-runner: 
{
    "error": "exit status 1",
    "fields.time": 41118903,
    "level": "error",
    "msg": "Machine creation failed",
    "name": "runner-yyehpyy-runners-dev-1676455996-da045408",
    "time": "2023-02-15T10:13:16Z"
}
```

Sometimes, I am getting also this error related to [Spot runner fails to deploy new runner #675](https://github.com/npalm/terraform-aws-gitlab-runner/issues/675)

```json
Feb 15 10:24:49 ip-10-0-1-238 gitlab-runner: 
{
    "driver": "amazonec2",
    "level": "info",
    "msg": "(runner-yyehpyy-runners-dev-1676456689-aefcc7c5) Missing instance ID, this is likely due to a failure during machine creation",
    "name": "runner-yyehpyy-runners-dev-1676456689-aefcc7c5",
    "operation": "create",
    "time": "2023-02-15T10:24:49Z"
}
```

runner module version `5.9.1`

**Comment by kayman-mk** [comment]
Hm, may be something with the merge train But I have no idea a) how it works and b) where I can see the results. I ask the maintainer to clarify.

**Comment by kayman-mk** [comment]
Shall be included in the latest version of GitLab docker+machine. But I think you won't get it running.

Please check #696 which posts a working configuration which fixes your problems.
