### ISSUE TITLE
Support for count property

### ISSUE THREAD

**Issue by hendrixroa** [npalm/terraform-aws-gitlab-runner#67]
Currently, I need to provision a gitlab-runner only for a stage, would be great if the module support count property to provisioning if the stage is "some"

**Comment by npalm** [comment]
Hi @hendrixroa 

Thanks for submitting an issue. Please can you elaborate a little bit more on the issue you have. The problem is not clear for me.

**Comment by hendrixroa** [comment]
Hi @npalm 
I mean, attribute count for aws resources like:

```hcl
resource "aws_instance" "web" {
  # Create one instance for each hostname
  count     = "${length(var.hostnames)}"

  # Pass each instance its corresponding template_file
  user_data = "${data.template_file.web_init.*.rendered[count.index]}"
}
```

**Comment by hendrixroa** [comment]
I can do a pull request if you want @npalm

**Comment by npalm** [comment]
@hendrixroa feel free to create a PR

Do you have any thoughts about another implication? Like all runner instance uses the same cache. Which could be fine.

**Comment by hendrixroa** [comment]
Yep, you are right, feel free to close this
