### ISSUE TITLE
failed to create new ec2-instances using gitlab-runner

### ISSUE THREAD

**Issue by dhinesh2287** [npalm/terraform-aws-gitlab-runner#683]
I have installed gitlab runner on my instance and register successfully with my gitlab project while building the job iam getting this issue
This creates an EC2 machine and soon after it destroys it and it keeps retrying.Can any one advise how to solve this issue
Info:
Docker version 20.10.7
docker-machine version 0.16.2-gitlab.12
Below which i given in my config file to create instance
![issue-03022023](https://user-images.githubusercontent.com/99251741/216522843-9e5ce08e-fbff-49d5-aae3-8c4059fd3413.png)

MachineOptions = ["amazonec2-access-key=xxx", "amazonec2-secret-key=yyy", "amazonec2-region=eu-west-1", "amazonec2-vpc-id=vpc-019c60666010b6c22", "amazonec2-subnet-id=subnet-08a01efe6b8c01294", "amazonec2-zone=a", "amazonec2-use-private-address=true", "amazonec2-tags=runner-manager-name,gitlab-aws-autoscaler,gitlab,true,gitlab-runner-autoscale,true", "amazonec2-security-group=isnc-sg-gl_runner", "amazonec2-instance-type=t3.large", "amazonec2-request-spot-instance=true", "amazonec2-spot-price=", "amazonec2-ami=ami-00e7df8df28dfa791"]

Thanks

**Comment by kayman-mk** [comment]
Did you check #680 #681 #675? High chance of a duplicate due to problems with the newest Docker release and the docker+machine.

**Comment by dhinesh2287** [comment]
I checked all the blog which you mentioned but getting the same error

**Comment by kayman-mk** [comment]
If you have some time, could you please upgrade to the latest versions of docker+machine, GitLab Runner, ...

Described in #696
