### ISSUE TITLE
Working configurations of docker+machine and GitLab Runner

### ISSUE THREAD

**Issue by kayman-mk** [npalm/terraform-aws-gitlab-runner#696]
Due to various problems with the docker+machine, GitLab Runner and Docker v23 release, I took some time to develop working configurations for spot and on-demand instances.

What I have running at the moment (spot and on-demand):

```hcl
version = "5.9.1"

docker_machine_options = ["engine-install-url=https://releases.rancher.com/install-docker/20.10.21.sh"]
docker_machine_version = "0.16.2-gitlab.15"
gitlab_runner_version  = "15.1.1"
```

Upgrading to the newest version of docker+machine will never work as long as you stay with the GitLab fork. You can use the following configuration:

```hcl
version = "5.9.1"

gitlab_runner_version       = "15.8.2"
docker_machine_download_url = "https://arr-cki-prod-docker-machine.s3.amazonaws.com/v0.16.2-gitlab.19-cki.2/docker-machine-Linux-x86_64"

# not needed if you run on-demand instances only; choose according to your setup
runner_instance_spot_price    = "100" # empty string/null does not work here!
docker_machine_spot_price_bid    = "100" # empty string/null does not work here!
```

The spot price bid issue is tackled in #697 

This version should also support the "new" AWS regions `eu-central-2`, ... But I wasn't able to check this.

**Comment by tmeijn** [comment]
Hey, I'm just trying out this module, have never used it before. For context.

I tried out these settings, but then it gave an error:

![image](https://user-images.githubusercontent.com/17970041/220120310-dd1a3548-db84-4b5d-94f6-5af9d02c7ca3.png)

And the error before that:

![image](https://user-images.githubusercontent.com/17970041/220120479-40092523-077d-4a79-9232-cd845d2555b3.png)

Using this setting:

```toml
docker_machine_spot_price_bid = "on-demand-price"
```

Resolves in the code to an empty string:

https://github.com/npalm/terraform-aws-gitlab-runner/blob/main/main.tf#L90

Which in the `config.toml` resolves to this:

![image](https://user-images.githubusercontent.com/17970041/220120959-19338d1f-d31f-4aea-8390-9cac60fe4b4f.png)

Setting this to a value (`0.3` in my example) resolved the issue and the machines could be created.

Hope this helps.

**Comment by kayman-mk** [comment]
Yeap, that's one of the problem with the CKI driver tackled in #697

**Comment by fknop** [comment]
I'm facing the same issue as @tmeijn, but even with a spot price defined in the configuration

**Comment by kayman-mk** [comment]
Ups! Fixed the issue description. Thanks @fknop

**Comment by kayman-mk** [comment]
Version v6.0.0 is released. Try to go without `docker_machine_download_url ` and `docker_machine_version` as long as you don't have specific needs. You don't have to modify the spot price setting. This was fixed within the module.
