### ISSUE TITLE
[docker+machine] Gitlab Runner is started before installation is finished

### ISSUE THREAD

**Issue by tmeijn** [npalm/terraform-aws-gitlab-runner#703]
# Describe the bug

## Summary

A premature start of the `gitlab-runner` service causes the Runner Manager to pick up jobs before the machine is actually ready to pick up jobs. This causes the jobs to get stuck: they seems to be executing on GitLab but they get stuck in pergatory because we then restart the `gitlab-runner` service.

## Walk along

When the Runner Manager is starting and the `userdata` scripts are executing, GitLab Runner is started before the actual installation is finished:

![image](https://user-images.githubusercontent.com/17970041/220432523-4a46b3d6-14ab-48de-b551-c2cdd59bceb2.png)

This causes the Runner Manager to pick up jobs and trying to create Machines, but it first fails because `docker-machine` executable is not yet installed because that happens later in the `userdata` script as can be seen below:

![image](https://user-images.githubusercontent.com/17970041/220433467-29ae4752-f8d4-453d-b427-68c578769ae1.png)

Here you can see that pending jobs have already been picked up while we are still creating a dummy machine:

![image](https://user-images.githubusercontent.com/17970041/220434376-064ee101-d0ae-4f16-b85b-54e783011e58.png)

Later in the `userdata` script we call `service gitlab-runner restart`:

![image](https://user-images.githubusercontent.com/17970041/220434651-52249832-8210-4873-b19c-e31b0ae61ee1.png)

Then the Runner manager is back up again but we can see that jobs that have been picked up are lost (`builds: "0"):

![image](https://user-images.githubusercontent.com/17970041/220435251-800fbc50-6acc-4614-b6b9-05ab67d1280a.png)

This causes the job that has been picked to get stuck:

![image](https://user-images.githubusercontent.com/17970041/220435883-7b00e46e-5473-4a5d-a308-77cf480e1b18.png)

# To Reproduce

1. Have jobs that are in a `stuck` state: no Runner can pick them up.
2. Provision a Docker Machine Runner Manager that would be able to pick up those `stuck` jobs
3. The jobs will get picked up by the Runner Manager prematurely
4. The jobs will go from `pending` to `running` but they will actually never execute

# Expected behavior

The `gitlab-runner` service should not start prematurely.

# Additional context

When we install the `gitlab-runner` package here:

https://github.com/npalm/terraform-aws-gitlab-runner/blob/1f75ba4a20a8b6ad0fb894c68005544469a10475/template/gitlab-runner.tpl#L82-L86

as a final step the `gitlab-runner` service actually get registered in systemd AND the service is started up. I think this is where the `gitlab-runner` service is actually started prematurely even before we have `docker-machine` installed.

I think a possible solution would be:

* Install all prerequisites (`docker-machine` + creating the dummy machine) before installing the actual `gitlab-runner` package
* Switch to a manual installation where we have control over when the `gitlab-runner` service gets started (main solution). See: https://docs.gitlab.com/runner/install/linux-manually.html#using-binary-file. In step 4 you can see you have to manually start the service, giving us more control.

Thanks for coming to my TED talk 😄

**Comment by kayman-mk** [comment]
Just checked my logs. Gitlab Runner is started as soon as it has been installed. Seems that this is triggered by `yum`. So either we should do a manual installation or install the docker+machine first.

What I see in my logs is, that `yum install gitlab-runner` installs some dependencies too. So the first choice should by changing the installation order.

**Comment by tmeijn** [comment]
@kayman-mk  Thanks, but I think that will only solve half the problem since we are also calling a `gitlab-runner restart` at the end of the userdata template as mentioned, which might also cause the gitlab-runner to lose the jobs if it managed to pick up the jobs in that short time.

**Comment by kayman-mk** [comment]
Yeah, good point. Discussion is continued in #704
