### ISSUE TITLE
Detect and retry when docker machine installation fails

### ISSUE THREAD

**Issue by eliasdorneles** [npalm/terraform-aws-gitlab-runner#72]
I started seeing this error in the Gitlab CI jobs, after updating the gitlab runner instance:

```
Running with gitlab-runner 11.10.1 (1f513601)
  on aws-spot-gitlab-runner DbkeXXxX
ERROR: Preparation failed: fork/exec /usr/bin/docker-machine: exec format error
Will be retried in 3s ...
ERROR: Preparation failed: fork/exec /usr/bin/docker-machine: exec format error
Will be retried in 3s ...
ERROR: Preparation failed: fork/exec /usr/bin/docker-machine: exec format error
Will be retried in 3s ...
ERROR: Job failed (system failure): fork/exec /usr/bin/docker-machine: exec format error
```

After some troubleshooting, I found out that the `docker-machine` binary was an HTML file:

```
# docker-machine ps
/usr/bin/docker-machine: line 1: syntax error near unexpected token `newline'
/usr/bin/docker-machine: line 1: `<!DOCTYPE html>'
```

Checking the contents of the file, I found a Github error page, which contained messages like this (content cleaned up for succintness):

```
...
    <title>GitHub — Unexpected problem serving your request</title>
...
      <h1>There was an unexpected problem serving your request</h1>
      <p>Please try again and contact us if the problem persists including 35FE:25F22:C675652:12DBD87E:5CED2B45 in your message</p>
...
```

It's a bit unexpected because judging from the code here: https://github.com/npalm/terraform-aws-gitlab-runner/blob/develop/template/gitlab-runner.tpl#L19 -- I'd expect the script to fail if the `curl` execution failed, but maybe it isn't failing if it gets a response, even if it's an error message?

**Comment by npalm** [comment]
@eliasdorneles thanks for reporting the issue. First idea that I have is to do a md5sum check, md5sums are available at the github release page https://github.com/docker/machine/releases

Do you have another idea?

**Comment by eliasdorneles** [comment]
Good idea, downloading the md5sum from `https://github.com/docker/machine/releases/download/v${docker_machine_version}/md5sum.txt` and then checking the file against it sounds great! :+1: 
Of course then md5 file download can fail, but we'd have a stronger guarantee.

Another idea (just whispered to me by @allan-simon) could be adding a `docker_machine_url` to allow users to host their docker machine binary themselves.

What do you think?

**Comment by npalm** [comment]
@eliasdorneles @allan-simon sounds good. In case the md5sum is invalid, a md5sum check will fail ass well. Another idea could be add the the `-f` option to `curl` to let it fail.

**Comment by eliasdorneles** [comment]
Oh yeah, that sounds like the minimal code which will reach most of the benefit, since it will show up in the logs and make the problem quicker to find. :+1: 
We can also enable retries -- I'll send a quick PR.
