### ISSUE TITLE
Convert module to support terraform 0.12

### ISSUE THREAD

**Issue by hendrixroa** [npalm/terraform-aws-gitlab-runner#73]
Terraform has launched the version 0.12, are you @npalm  planning move to terraform 0.12 ? 
I can do a pull request with the changes if you want.

**Comment by npalm** [comment]
@hendrixroa yes of course but did not had the time yet. Feel free to create a PR with changes

**Comment by npalm** [comment]
Just did a small experiment, due to the usages of count and the filter for selecting an IAM it looks like not possible to move to TF 0.12 without breaking backwards compatibility to 0.11.

**Comment by bishtawi** [comment]
If you look at some other popular Terraform modules (namely [AWS VPC](https://github.com/terraform-aws-modules/terraform-aws-vpc) and [AWS RDS](https://github.com/terraform-aws-modules/terraform-aws-rds)), they maintain two versions of their modules. V1 of their modules map to 0.11 of Terraform, and V2 maps to 0.12.

**Comment by npalm** [comment]
@bishtawi thanks for the note. I am actually have that in mind. Do you als know a tool to generate docs from the variables that supports TF 0.12. I am using terraform-docs which is still broken for 0.12.

**Comment by npalm** [comment]
Started with the conversion

**Comment by npalm** [comment]
All sources are converted including samples.

**Comment by npalm** [comment]
Tested state mirgration for the public example. For some reason it needs to replache the launch config based on the user_data script. But besides that all works fine

**Comment by hendrixroa** [comment]
Sounds great. Looks like that they will launch a new fix version, we should wait by them.

**Comment by hendrixroa** [comment]
Sorry by the late response

**Comment by waeltken** [comment]
Could we release a RC version in the meantime?

**Comment by npalm** [comment]
Create a project with the current left overs
- sync last modification to 0.11 code base
- get doc generation working

**Comment by npalm** [comment]
> Could we release a RC version in the meantime?

https://github.com/npalm/terraform-aws-gitlab-runner/releases/tag/4.0.0_M1

**Comment by npalm** [comment]
Just created 4.0.0_M2

**Comment by npalm** [comment]
> Could we release a RC version in the meantime?

@waeltken in case you are trying the RC version, please could you give some feedback?

**Comment by kevinrambaud** [comment]
Looks like the terraform-0.12 branch is 26 commits behind develop. What's your strategy to include the recent changes on this branch? I'm up to start using the 0.12 branch but I need at least the 2 changes I made you merged.

**Comment by npalm** [comment]
@kevinrambaud the TF 0.12 branch should be in sync with develop. i merged the all manually. You can see in the commits on the tF0.12 branch the merged PR's and issues. The change to HCL2 make merges quite hard, so did all quickly manually.

Please let me know if you miss anything?

**Comment by kevinrambaud** [comment]
Oh right, I didn't check the commits themselves. Looks good to me. There is one last customization I would need to rely fully on this module, the customization of the `volumes` list in the runner.tpl. I played a little bit with it to implement it but it's not as smooth as I thought it would be. As template_file does not support anything else than primitive values, list and map cannot be used. `jsonencode` is not an option and using a kind of custom `join` did not work for me.

Are you familiar with this problem? Example https://github.com/kevinrambaud/terraform-aws-gitlab-runner/commit/90fb3daa53c09c1b8627a61c81c5ba38844c2ca6

**Comment by npalm** [comment]
@kevinrambaud thanks for the note. I have synced the branch with develop. I hope to switch by default in a the coming weeks to terraform 0.12. Still looking for some feedback. Also need to fix some types.

I sent you a short message on gitter as well.

**Comment by kevinrambaud** [comment]
Awesome, I'm gonna check your message, thanks.

**Comment by npalm** [comment]
The module is ready and will be released shortly. A branch will remain for terraform 0.11 support

**Comment by npalm** [comment]
Release 4.0.0
https://github.com/npalm/terraform-aws-gitlab-runner/releases/tag/4.0.0
