### ISSUE TITLE
Allow spot requests in multiple availability zones

### ISSUE THREAD

**Issue by declension** [npalm/terraform-aws-gitlab-runner#76]
### Background
At $WORK, we have a pre-defined VPC, and one subnet within that (but want more to avoid any further capacity issues) for Gitlab & runners. 

Having multiple AZs is entirely possible, as the spot request wizard has checkboxes for each:

![image](https://user-images.githubusercontent.com/3322808/58792375-f6723780-85eb-11e9-8994-deee96fd624a.png)
 

### Proposal
 * Multiple availability zones (via `aws_zone`) can be specified as parameters, *or*
 * Multiple subnets (via a new `subnet_ids_runners` perhaps?) in various AZs, with the AZ inferred automatically, so deprecating `aws_zone` perhaps?

### Notes
I don't know if this necessarily makes sense, but am definitely keen to find ways to improve our `capacity-not-available` problems (not pricing), and this seems like one major cause

**Comment by declension** [comment]
Hmm, https://github.com/docker/machine/pull/4701 looks quite relevant / concerning...

**Comment by npalm** [comment]
@declension you can spin now a runner in multiple zones, would this help see #77  and PR #96

**Comment by declension** [comment]
Thanks @npalm, we'll try this soon. Closing for now
