### ISSUE TITLE
Allow multiple runner instance types

### ISSUE THREAD

**Issue by declension** [npalm/terraform-aws-gitlab-runner#77]
### Background
When adding only one instance type for a spot request (in the wizard), it becomes clear this is affecting the availability (which brings down our gitlab runners sometimes with `capacity-not-available`)
![image](https://user-images.githubusercontent.com/3322808/58792708-9d56d380-85ec-11e9-8d13-dc09b54801c7.png)
See related #76 

### Proposal
 * Deprecate `instance_type` in favour of `instance_types`, a list (e.g. `instance_types = ['m4.large', 'm5.large']`, and, err, somehow make this work downstream...

### Notes
This probably isn't possible [until Fleets / multiple instance types are supported in `docker-machine`](https://github.com/docker/machine/issues/4588), unless perhaps it could be done manually, or within Gitlab Runner itself somehow... :thinking:

**Comment by npalm** [comment]
Thanks, already cracking my thoughts on this topic. Please let me know if you have any other idea. 

Options could be running multiple runners with different configs, but problem will be that unhealty runners will have stucked build. So maybe an agent as watcher or lambda to take the out of the healthy runner agent pools

**Comment by npalm** [comment]
@declension the runner supports now multiple instance. You can create multiple runners and share the cache.  See the example in `examples/runner-public`.

**Comment by declension** [comment]
Great - we'll try this soon. Thanks @npalm

**Comment by npalm** [comment]
@declension shall I close the issue?

**Comment by DavidGamba** [comment]
@npalm does this work when you have exactly the same tags for the multiple instances?
Or will GitLab be stuck with the instance it first picked until it times out?

**Comment by npalm** [comment]
> @npalm does this work when you have exactly the same tags for the multiple instances?
> Or will GitLab be stuck with the instance it first picked until it times out?

Not sure, guess the build will be picked by the runner that is polling first.
