### ISSUE TITLE
Receiving 403 forbidden for shared cache

### ISSUE THREAD

**Issue by mbluemer** [npalm/terraform-aws-gitlab-runner#78]
Using mostly the default setup with v3.3.0 and the jobs keep getting a `403 forbidden` when trying to access the shared s3 cache. I checked the `docker-machine-role` assuming it would give each runner permission to access the cache but it looks like there are no permissions attached to that role by default. I tested out explicitly adding a `s3:*` permissions to that role just to see if that would make things work and I'm still getting 403s on cache pull.

Any ideas?

**Comment by npalm** [comment]
@mbluemer by default I am testing the runner with the default setup in example. Next I run a build with two steps. First step write to cache, second step read from cache. This works fine. Can you give it a try with the default setup, see the examples?

**Comment by npalm** [comment]
@mbluemer see here the latest run of my test build https://gitlab.com/codethebuild/gitlab-cache/pipelines/63157591

**Comment by mbluemer** [comment]
Trying narrowing settings down so that I was closer to the default but still getting 403s. I'm using a private GitLab instance though that shouldn't affect things in any significant way. Here's the configuration I'm using:

```terraform
provider "aws" {
  region = "eu-west-1"
}

data "aws_vpc" "primary" {
  tags {
    Name = "PrimaryVPC"
  }
}

data "aws_subnet_ids" "private_subnets" {
  vpc_id = "${data.aws_vpc.primary.id}"

  tags {
    Name = "*Private*"
  }
}

data "aws_subnet_ids" "public_subnets" {
  vpc_id = "${data.aws_vpc.primary.id}"

  tags {
    Name = "*Public*"
  }
}

module "runner" {
  source  = "npalm/gitlab-runner/aws"
  version = "3.3.0"

  aws_region  = "eu-west-1"
  environment = "gitlab-runner"

  ssh_public_key = "${var.ssh_public_key}"  # Set in GitLab variables

  vpc_id                   = "${data.aws_vpc.primary.id}"
  subnet_ids_gitlab_runner = ["${data.aws_subnet_ids.private_subnets.ids}"]
  subnet_id_runners        = "${element(data.aws_subnet_ids.private_subnets.ids, 0)}"
  aws_zone                 = "b"

  runners_name          = "Autoscaling Runner"
  runners_gitlab_url    = "https://<company domain>.gitlab.io"

  gitlab_runner_registration_config = {
    registration_token = "${var.registration_token}" # Set in GitLab variables
    description        = "Autoscaling runner"
    tag_list           = "docker"
    locked_to_project  = "false"
    run_untagged       = "true"
    maximum_timeout    = "3600"
  }

  enable_gitlab_runner_ssh_access = true

  runners_off_peak_timezone   = "EST"
  runners_off_peak_idle_count = "1"
  runners_off_peak_idle_time  = "300"
  # To account for multiple time zones start peak at 8am India time and end 6pm EST
  runners_off_peak_periods    = "[\"* * 0,18-22 * * mon-fri *\", \"* * * * * sun *\", \"* * 0-22 * * sun *\"]"
}
```

**Comment by mbluemer** [comment]
I'm realizing this makes sense as the default expected behavior is to be using publicly accessible buckets so no authentication shouldn't be necessary. For a private organization having those caches exposed isn't an option. We also need to make modifications to the security groups so that the runner and instances are only accessible from within our VPC so I'll probably fork anyway and make the necessary modifications.

If you don't have plans to support these changes feel free to close this ticket.

**Comment by mbluemer** [comment]
Sorry further clarification after reading into the repo, we need the ability to specify  a `source_security_group_id` for the port 22 ingress policies.

Also noticing that `private: true` is the default on the bucket. Also there's a `docker_machine_cache_policy` that should give the runners access to the cache? Need to dig a little deeper into this...

**Comment by npalm** [comment]
Yes the bucket created by the module should be private, the policy to access the bucket is set to the runner agent instance. And NOT to the docker machine. It is strange, but working in this case.  It is also not clear to me why the gitlab runner cache is handles by the agent and not by the de runner (docker-machine itself).

The example you find in the examples dir named default is running in private subnet, having a cache that is private.

**Comment by mbluemer** [comment]
Yeah after reading deeper into the Gitlab Runner documentation I realized they specify that the IAM role should be on the runner so things are right there. Not sure why I'm still getting 403 forbidden but I don't have the time to investigate that further now so I've just implemented a workaround to use an AWS access key.

I did implement a [toggle on bucket versioning](https://github.com/mbluemer/terraform-aws-gitlab-runner/commit/4cf098234f030ebae21e45e1c9ec2066ad96c0cc) (we enable this for security reasons) and [tighter rules for the instances with an option to use source security groups on the runner](https://github.com/mbluemer/terraform-aws-gitlab-runner/commit/db7df68ff92c99f24c01ba80aabcff008b190ba9) because we'd like to only have our instance accessed from a bastion host. If you're interested in either I'd be happy to open MRs that are cleaned up and update the documentation. Just let me know.

Since I'm unsure of the source of the original issue and don't have time to fix it I'll go ahead and close this. Thanks for the time and help!

**Comment by npalm** [comment]
@mbluemer thanks for the feedback. 

The runner in the default example should run in a private subnet, and even ssh access can be siabled. This isstance as well the docker machine instances are only reachable withing the vpc (via a bastion). 

By configuring the private subnets for the runner and the docker machines you instances should not be reachable from outside the VPC. 

I would be great if you could make some time to improve the docs and helps others in the future. Thanks once again

**Comment by NikolaiGulatz** [comment]
I am experiencing the following, behaviour:

I am using a shared S3 cache for the runners. After deploying the runners for the first time, cache and cache extraction worked for the first 2 pipelines. For all subsequent pipelines however, cache extraction failed with:

```
Checking cache for c994fbe3e8856e65a0408a1299deb49139532944-2...
FATAL: received: 403 Forbidden                     
Failed to extract cache
```

Uploading the cache works, however. Any ideas?
