### ISSUE TITLE
Volume size

### ISSUE THREAD

**Issue by daanielcarvalho** [npalm/terraform-aws-gitlab-runner#80]
Hi

How can i change a volume size of the instance created? there is no option!

Thanks in advance
Daniel

**Comment by npalm** [comment]
@daanielcarvalho you can set the variable `runners_root_size`. It is used for setting the size of the disk of the docker-machine instances.

**Comment by daanielcarvalho** [comment]
Hi

I use runners_root_size = "30" and I still get 8gb machine running.
![Screenshot 2019-06-06 at 09 14 15](https://user-images.githubusercontent.com/6240971/59017539-a689af80-883b-11e9-8d49-d87ba2202faa.png)

Thanks in advance
Daniel

**Comment by npalm** [comment]
Hi Daniel @daanielcarvalho 

Is this the instance that is used for the agent? Or is this an instance used for hosting the runners. Typically a spot instances managed via docker-machine? In case this spot instance disk is not changed, please can you check if the root size is set in the user_data script in the launch coniguration.

If you would like to change the size of the disk of the instance hosting the agent, you have to create a change in the source. Feel free to propose a PR

**Comment by daanielcarvalho** [comment]
Hello

this is for the instances that will run the docker image with runner specifications!

Thanks
Daniel

**Comment by npalm** [comment]
@daanielcarvalho a bit late response. Just verified and it works as documented. By setting `runners_root_size = 25` the seize of the volume is 25 GB for example

![image](https://user-images.githubusercontent.com/11609620/61958862-77cdc100-afc2-11e9-8f6c-ab6ce852854c.png)

**Comment by npalm** [comment]
I will close the issue for now, Thanks for reporting

**Comment by bsuv** [comment]
@npalm this is not resolved! I just set the value of `runners_root_size` in a v4.1.0 module instance and *still* got only 8 GB. 

I hope it's fine with you if I submit a PR replacing LCs with LTs and also using an input variable for setting root block device size at LT-time instead of boot time.

**Comment by npalm** [comment]
@bsuv Thank you for reporting. The runner setup supports two modes, See the scenario's mentionin the readme.

In the first mode the builds are scheduled via a docker machine on spot instances. The `runners_root_size` sized is used for the spot instances hosting docker machine (see sample runner-default). In the thirds scenario builds are running on the the instance created by the auto scaling group via docker. for that instance the size is currently not configurable (see example runner-docker).

So feel free to propose PR's for:
- make the size of the runner agent instance configurable / instance used for build when executor is `docker`.
- convert Launch group to Lauch template. 

Would be great if you can split them in 2 PR's
