### ISSUE TITLE
Misleading Variable-Description

### ISSUE THREAD

**Issue by solutionDrive-Alt** [npalm/terraform-aws-gitlab-runner#85]
Hello, 
Thanks for this awesome Module.

While trying it out I ran into a problem. The description of the variable `enable_manage_gitlab_token` is kind of misleading.

```
variable "enable_manage_gitlab_token" {
  description = "Boolean to enable the management of the GitLab token in SSM. If `true` the Gitlab token will be managed via terraform state. If `false` the token will still be stored in SSM however, it will not be managed via terraform."
  default     = true
}
```

The first sentence of the description states, that this will enable the management via `SSM`. But the following sentences are implying the opposite.

As I want to manage it in `terraform` I thought the default-value would be great, when reading the description (aside the first sentence) in conjunction with the variable_name (since we are in terraform and i would like to enable the management via terraform)

Looking at `main.tf` it gets clear, that the first sentence of the description is telling the truth.

Besides the semantical point of view the description should be updated anyways imho.

Best regards

**Comment by npalm** [comment]
@solutionDrive-Alt thanks for the remark. Feel free to create a PR. Otherwise I will do my best to update the docs in the next weeks

**Comment by solutionDrive-Alt** [comment]
@npalm I just created the PR #86 for that.

**Comment by npalm** [comment]
Fixed
