### ISSUE TITLE
2 instances of this module can not share the same cache-bucket

### ISSUE THREAD

**Issue by solutionDrive-Alt** [npalm/terraform-aws-gitlab-runner#91]
Hi,

when I use your module twice, so I can use different sizes of instances for different jobs, I see no possibility to use the same bucket as `cache`.

The reason for this, is the fact that the module will always try to create a bucket, but if this bucket already exists, terraform will fail.

Maybe it makes sense to remove the `cache`-bucket from this module and better inject a cache_bucket-name into the module as parameter to be able to get the required information of the bucket inside of the module.

I tried to work around this issue, by introducing a `count`-variable for the bucket in conjunction with an extra parameter, but that forced me to add `count`-variables to most of the other resources too, which enforces a lot of duplication.

**Comment by npalm** [comment]
Thanks for creating the issue. Yep I am aware of the limitation. It also crossed my mind. I had the thought not to remove the bucket but made a more a submodule. Which you have to instantiate specific. The output of this submodule can then be based to the runner module it self.

Maybe in such way that by default the bucket is created and it is the the user to to disable the creation and control the management of the the bucket outside het module.


```
module "bucket" {
...
}

module "runner1" {
...
   bucket.arn
   bucket.policy
}


module "runner2" {
...
   bucket.arn
   bucket.policy
}
```

**Comment by npalm** [comment]
@solutionDrive-Alt I have a first "early" setup working for 2 nodes, one cache. Feel free to have a look. The public example contains a sample setup. I will update the sample later so the cache will be create separated (outside) the runner. And policy and bucket details will be injected.

**Comment by solutionDrive-Alt** [comment]
@npalm I checked it out and this looks very promising. I will have a closer look in the next days and will try it with my setup.
Thanks for working on this already!

**Comment by npalm** [comment]
@solutionDrive-Alt thanks for the quick answer, it as already on my list for some time.
